//go:build go1.22

// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// Defines values for HealthResponseChecks.
const (
	Down HealthResponseChecks = "down"
	Up   HealthResponseChecks = "up"
)

// Valid indicates whether the value is a known member of the HealthResponseChecks enum.
func (e HealthResponseChecks) Valid() bool {
	switch e {
	case Down:
		return true
	case Up:
		return true
	default:
		return false
	}
}

// Defines values for HealthResponseStatus.
const (
	Ok          HealthResponseStatus = "ok"
	Unavailable HealthResponseStatus = "unavailable"
)

// Valid indicates whether the value is a known member of the HealthResponseStatus enum.
func (e HealthResponseStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	case Unavailable:
		return true
	default:
		return false
	}
}

// Defines values for OrderStatus.
const (
	Cancelled OrderStatus = "cancelled"
	Expired   OrderStatus = "expired"
	Paid      OrderStatus = "paid"
	Pending   OrderStatus = "pending"
)

// Valid indicates whether the value is a known member of the OrderStatus enum.
func (e OrderStatus) Valid() bool {
	switch e {
	case Cancelled:
		return true
	case Expired:
		return true
	case Paid:
		return true
	case Pending:
		return true
	default:
		return false
	}
}

// Checkout defines model for Checkout.
type Checkout struct {
	// CheckoutUrl URL HTTPS hospedada pela Stripe.
	CheckoutUrl string `json:"checkoutUrl"`

	// ExpiresAt Instante em que a sessao deixa de aceitar pagamento.
	ExpiresAt time.Time `json:"expiresAt"`
}

// CreateOrderRequest defines model for CreateOrderRequest.
type CreateOrderRequest struct {
	// ProductId Identificador de um produto conhecido pelo servidor.
	ProductId string `json:"productId"`

	// Quantity Quantidade de unidades do produto.
	Quantity int `json:"quantity"`
}

// Error defines model for Error.
type Error struct {
	// Code Codigo estavel do erro, adequado para tratamento programatico.
	Code string `json:"code"`

	// CorrelationId Identificador de correlacao da requisicao, igual ao header X-Correlation-ID.
	CorrelationId string `json:"correlationId"`

	// Message Descricao legivel do erro, sem dados sensiveis.
	Message string `json:"message"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Checks  map[string]HealthResponseChecks `json:"checks"`
	Service string                          `json:"service"`
	Status  HealthResponseStatus            `json:"status"`
	Version string                          `json:"version"`
}

// HealthResponseChecks defines model for HealthResponse.Checks.
type HealthResponseChecks string

// HealthResponseStatus defines model for HealthResponse.Status.
type HealthResponseStatus string

// Order defines model for Order.
type Order struct {
	// Amount Valor total na menor unidade da moeda, calculado no servidor.
	Amount int64 `json:"amount"`

	// Currency Codigo ISO 4217 da moeda.
	Currency string `json:"currency"`

	// Id Identificador publico opaco e nao sequencial.
	Id string `json:"id"`

	// Status Estado comercial do pedido.
	Status OrderStatus `json:"status"`
}

// OrderStatus Estado comercial do pedido.
type OrderStatus string

// IdempotencyKey defines model for IdempotencyKey.
type IdempotencyKey = string

// OrderId defines model for OrderId.
type OrderId = string

// CreateOrderParams defines parameters for CreateOrder.
type CreateOrderParams struct {
	// IdempotencyKey Chave opaca escolhida pelo cliente que identifica esta operacao. Deve
	// ter entre 1 e 255 caracteres. Reenviar a mesma chave nao cria um
	// segundo pedido.
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// CreateCheckoutParams defines parameters for CreateCheckout.
type CreateCheckoutParams struct {
	// IdempotencyKey Chave opaca escolhida pelo cliente que identifica esta operacao. Deve
	// ter entre 1 e 255 caracteres. Reenviar a mesma chave nao cria um
	// segundo pedido.
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// CreateOrderJSONRequestBody defines body for CreateOrder for application/json ContentType.
type CreateOrderJSONRequestBody = CreateOrderRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetHealth Retorna a disponibilidade do processo e de suas dependencias.
	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// CreateOrder Cria um pedido a partir de um produto conhecido pelo servidor.
	// (POST /v1/orders)
	CreateOrder(w http.ResponseWriter, r *http.Request, params CreateOrderParams)
	// GetOrder Retorna o estado local atual de um pedido.
	// (GET /v1/orders/{orderId})
	GetOrder(w http.ResponseWriter, r *http.Request, orderId OrderId)
	// CreateCheckout Cria ou recupera uma sessao hospedada de pagamento.
	// (POST /v1/orders/{orderId}/checkout)
	CreateCheckout(w http.ResponseWriter, r *http.Request, orderId OrderId, params CreateCheckoutParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateOrder operation middleware
func (siw *ServerInterfaceWrapper) CreateOrder(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateOrderParams

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateOrder(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetOrder operation middleware
func (siw *ServerInterfaceWrapper) GetOrder(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "orderId" -------------
	var orderId OrderId

	err = runtime.BindStyledParameterWithOptions("simple", "orderId", r.PathValue("orderId"), &orderId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "orderId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetOrder(w, r, orderId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateCheckout operation middleware
func (siw *ServerInterfaceWrapper) CreateCheckout(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "orderId" -------------
	var orderId OrderId

	err = runtime.BindStyledParameterWithOptions("simple", "orderId", r.PathValue("orderId"), &orderId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "orderId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateCheckoutParams

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateCheckout(w, r, orderId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/health", wrapper.GetHealth)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/orders", wrapper.CreateOrder)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/orders/{orderId}", wrapper.GetOrder)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/orders/{orderId}/checkout", wrapper.CreateCheckout)

	return m
}

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200JSONResponse HealthResponse

func (response GetHealth200JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealth503JSONResponse HealthResponse

func (response GetHealth503JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type CreateOrderRequestObject struct {
	Params CreateOrderParams
	Body   *CreateOrderJSONRequestBody
}

type CreateOrderResponseObject interface {
	VisitCreateOrderResponse(w http.ResponseWriter) error
}

type CreateOrder201JSONResponse Order

func (response CreateOrder201JSONResponse) VisitCreateOrderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateOrder400JSONResponse Error

func (response CreateOrder400JSONResponse) VisitCreateOrderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateOrder401JSONResponse Error

func (response CreateOrder401JSONResponse) VisitCreateOrderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateOrder404JSONResponse Error

func (response CreateOrder404JSONResponse) VisitCreateOrderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type CreateOrder409JSONResponse Error

func (response CreateOrder409JSONResponse) VisitCreateOrderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type CreateOrder413JSONResponse Error

func (response CreateOrder413JSONResponse) VisitCreateOrderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(413)
	_, err := buf.WriteTo(w)
	return err
}

type CreateOrder500JSONResponse Error

func (response CreateOrder500JSONResponse) VisitCreateOrderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetOrderRequestObject struct {
	OrderId OrderId `json:"orderId"`
}

type GetOrderResponseObject interface {
	VisitGetOrderResponse(w http.ResponseWriter) error
}

type GetOrder200JSONResponse Order

func (response GetOrder200JSONResponse) VisitGetOrderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetOrder401JSONResponse Error

func (response GetOrder401JSONResponse) VisitGetOrderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetOrder404JSONResponse Error

func (response GetOrder404JSONResponse) VisitGetOrderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetOrder500JSONResponse Error

func (response GetOrder500JSONResponse) VisitGetOrderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type CreateCheckoutRequestObject struct {
	OrderId OrderId `json:"orderId"`
	Params  CreateCheckoutParams
}

type CreateCheckoutResponseObject interface {
	VisitCreateCheckoutResponse(w http.ResponseWriter) error
}

type CreateCheckout201JSONResponse Checkout

func (response CreateCheckout201JSONResponse) VisitCreateCheckoutResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateCheckout400JSONResponse Error

func (response CreateCheckout400JSONResponse) VisitCreateCheckoutResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateCheckout401JSONResponse Error

func (response CreateCheckout401JSONResponse) VisitCreateCheckoutResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateCheckout404JSONResponse Error

func (response CreateCheckout404JSONResponse) VisitCreateCheckoutResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type CreateCheckout409JSONResponse Error

func (response CreateCheckout409JSONResponse) VisitCreateCheckoutResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type CreateCheckout500JSONResponse Error

func (response CreateCheckout500JSONResponse) VisitCreateCheckoutResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type CreateCheckout502JSONResponse Error

func (response CreateCheckout502JSONResponse) VisitCreateCheckoutResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(502)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// GetHealth Retorna a disponibilidade do processo e de suas dependencias.
	// (GET /health)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
	// CreateOrder Cria um pedido a partir de um produto conhecido pelo servidor.
	// (POST /v1/orders)
	CreateOrder(ctx context.Context, request CreateOrderRequestObject) (CreateOrderResponseObject, error)
	// GetOrder Retorna o estado local atual de um pedido.
	// (GET /v1/orders/{orderId})
	GetOrder(ctx context.Context, request GetOrderRequestObject) (GetOrderResponseObject, error)
	// CreateCheckout Cria ou recupera uma sessao hospedada de pagamento.
	// (POST /v1/orders/{orderId}/checkout)
	CreateCheckout(ctx context.Context, request CreateCheckoutRequestObject) (CreateCheckoutResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(w http.ResponseWriter, r *http.Request) {
	var request GetHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateOrder operation middleware
func (sh *strictHandler) CreateOrder(w http.ResponseWriter, r *http.Request, params CreateOrderParams) {
	var request CreateOrderRequestObject

	request.Params = params

	var body CreateOrderJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateOrder(ctx, request.(CreateOrderRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateOrder")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateOrderResponseObject); ok {
		if err := validResponse.VisitCreateOrderResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetOrder operation middleware
func (sh *strictHandler) GetOrder(w http.ResponseWriter, r *http.Request, orderId OrderId) {
	var request GetOrderRequestObject

	request.OrderId = orderId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetOrder(ctx, request.(GetOrderRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetOrder")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetOrderResponseObject); ok {
		if err := validResponse.VisitGetOrderResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateCheckout operation middleware
func (sh *strictHandler) CreateCheckout(w http.ResponseWriter, r *http.Request, orderId OrderId, params CreateCheckoutParams) {
	var request CreateCheckoutRequestObject

	request.OrderId = orderId
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateCheckout(ctx, request.(CreateCheckoutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateCheckout")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateCheckoutResponseObject); ok {
		if err := validResponse.VisitCreateCheckoutResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7FndUiQ30n2VDH2+LKB/YAz9XWHsXRM7EWDwbDiCYYlsKbtbpkpZSKr2YKLffUMqVfVfMdALs7sXe0dT",
	"JSnz6OjkSdWTkFyUbMh4J0ZPokSLBXmy8de5oqJkT0Y+/o0ew38UOWl16TUbMRJnM5wTcIkSgZzkfKYV",
	"Qkk5g8w1GU/wUBFoRcbriY5veQQuyaJE3ocfaU6fjScLZLwl6APB4OgIJFqUniy5fbgiMnONFhAKcgWC",
	"jKsaZJBWI1TFZ+NoWhnFUJLSivc/G5EJ+oJFmZMYiWPZnxxNBrR3gsPx3qEcqL1j+n6y18fBeCgP1RF9",
	"mIhM6JDSjFCRFZkwWISxKxDsBQwyYemh0paUGHlbUSacnFGBAZwCv3wkM/UzMRocHWWi0Kb53c+EfyzD",
	"hM5bbaZiscjEhVVkz9U2ructYIotlNU415IjzgzLLNdyZKvuhpPBUe+QeoeT45N+Xw1PsCd7w94RHQ/k",
	"cNjrNzmW6GfLDDlF8bXMSvSebBj7j7DQTW/vBPcmt0/DweI7sZ3aohkbWXQ2I3nPlY8T2bD5XlN8ItOT",
	"TzbfBuHT1Uf4+ddfL69hxq4khTW1EK691SWF9CdsC/RiJCqrt8MI8JTakjv1HRAb5zEQlIrIUQRHziGD",
	"Iv0FQRGgJO3RQolTLMh4XltRoac9rwsSXTu7RPJmLcnVkG7bgTz+naQPAZ9ZQk+RF1f0UJHrAK20rCrp",
	"X+aNIqgKiK97BslmRlJH+uQMjuxcK7YhqRXe9gfHL/A2Ew8VGq99hx78Ep8oVBQXN/FPFylbR5FW00VV",
	"iFG/1+vFxdLPdiltPE3JbiG5zHwliC4Yf7KWbQfdWFGHiLHSU47KNKc8BEvWcgao6KHCEDtaBG/R1zQI",
	"uUwtFui1jAltASTZWsoxzP+qXUrvy8A+hJix0xI5Az2tMAdkqGUJfts7W869d/5j5/JFIPK0I9Mf46+w",
	"TE5TvZasowIUKnbgyDg9J+32X2Z2wHO53mbiXTvzM2HuZ1fkSjaOnlGE+BcqpcNEmF+uvUEmkOVGVKXI",
	"hOI/jLjdirNj4ch3GVfcetl59NXa5HwvMlEZnKPOcZxT5xpzsi4C+/QCTmn+ZRDLsVmTcRdYUQe2McKC",
	"K9MhaX/HnC149piDCcXSsG0OYSBWwaQwA4m5rPJAbLMuA622aeM/HIrt45gJWVkbSuGzp+j8+gIOB/3v",
	"2/U6Gap3rHl1tXdBEY3UmHdOutzF7yxNxEj838HS2xykenQQMb2uX93cJ61EttysBPNK0s/u0XW79HpO",
	"PzkfcJZckA1xbxTvRLaSjAo5ZKLEGIJEIynPSbX1QnUQMJJaVlb7x+uQXE2OuFk2HsHTUn/FtTmSljyG",
	"kMYo78koSGMTHTrt0G97p5fnyQileLBeJlZ9bSa8veDp5XkUsJycC3pnaUI27mStrWldyRQfrxVcr330",
	"N5f4GP7n4AfWOdkyR09wenm+cpZGorff3++FXeGSDJZajMQw/iuLnicCdDCLEhT+nFI8RdGONmIt/kq+",
	"FqloiGqdigMHvV5dRIyn+vhhWeZaxqEHv7taCZae6Wss3JDBiN06ZpeWJTkXq00sOgEoS5LGZEMxGmM+",
	"4/2Q61Fv+G+M61MRzFGgbL2BPLZ6ip6DE4/mXhulw/BQX/bXWCpGN7eZcFVRoH0UI3FFnq1BQEgjxjpP",
	"YhXTrvOPVsJV6FaXrYsTTl04PxfN/jlxG9Y7mPcPoqmt7RK7Dq28gHlUS4KkU8ujCcEFtiLpVlUSImG9",
	"tqD4s5HoMecp78NF2+6EA2ALBAwEdNAan7jQQ2uP/h8MmVnoXFIYocMJirxa/iF50CggYSaSqbVZZ+yK",
	"aRTZWgd3073by1cONjq8xW2tiOT8D6weX8Gr1IEk8Svi6V9u8ael/4yesGDjfN37hYOLeUUblrb5+y5O",
	"tmo2+yt9xUs87vDRi8Vis8NZbJ3w/o4ZN9I9elom05TnYG97qyVT/HD1UdTF77XtWlPT2oV2wKAmRJe0",
	"1DQPzXNdnNJZeMYYLDJx2OvtCIwOxNbql5VWoQWotuHNK3eJb1v2cSQ+TPpqIHt4OD6mw8kHeaL6NJgM",
	"8XB8JD+o71e956glChSV8zAmGJP/g8hAH9AoCLuxC3p1C9GB3hnbkrPGkHMFEouS3bpzh5Qcu4TfrsSq",
	"DFZ+xlb/SaoLvLXnb0QuzETGp3CgPSPvglb0GoraGo8MWLmolVw1MGFC6XBnlO4N/2Eua8nowqlRE8P+",
	"bsKVeTNYaUIw7KGe8D1gumhlMhWQWAsY6It2nsJ5bItNjdTJjkhZqhypZAe3TuKyCNzd0+OdZDPJtXzz",
	"kVyZF+7pETC3hOoRQijvAtspbFzPwe8IE9ZQuXhbxOGAers03QG7/nBH7DzzR7RT6oTufUUsTQNjVo/g",
	"mSGPC78PxWRQrg2doi+SFAFDrgvtW8MR79lOL8+Twdxd/T1Zg3k3YvWzO4qRvpViaTagZd5vBOovmM+C",
	"jSVXkg00ShfNFlZ4tFg1smf1NXR6umISX3sB1zrZ2rVuuNiDp3RFu/ha09L4v2/Ws7zkJ8iEZSwq3qHm",
	"/deVlzcGlLAwuIXHUa/37Zfv5C4bV+X+K/xtGrH6ElQx5CzDtaMPl4+JxO2txRZXd205mq8ei9tnWH4g",
	"Vz8Y/ItzZ880fp8cBtHLK6fn8ZYhiN9mL1iSddp5ndq/lDxcUUnhXONnU3+J2qw+sUnn+JmqGQWK5pzP",
	"Vz4wsNVTbTB/vpVrP5i8Sze3c4PzyharCbKDhtfNpxRo3qqvMbC5xlDaktRsmnueV/cYbzwfP9euXcVv",
	"kgkqjR2S8T8N69Kw1/nOd8HDUuV1rv8MIkbFmo3LoFxGGC4Lw5cMrtI7jXgAej3/D0uvNlrWxqGJKsUz",
	"+PbxxJZiTukTU3un6iJqtSooqmL7XxWtOLVc2zY4XIElWYXsVkcsP85uXd2mStFc3QZfs34d2HldfXMb",
	"dCvYo0b1KpuLkTgIFeOfAwA=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
