//go:build go1.22

// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// Defines values for HealthResponseChecks.
const (
	Down HealthResponseChecks = "down"
	Up   HealthResponseChecks = "up"
)

// Valid indicates whether the value is a known member of the HealthResponseChecks enum.
func (e HealthResponseChecks) Valid() bool {
	switch e {
	case Down:
		return true
	case Up:
		return true
	default:
		return false
	}
}

// Defines values for HealthResponseStatus.
const (
	Ok          HealthResponseStatus = "ok"
	Unavailable HealthResponseStatus = "unavailable"
)

// Valid indicates whether the value is a known member of the HealthResponseStatus enum.
func (e HealthResponseStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	case Unavailable:
		return true
	default:
		return false
	}
}

// Defines values for OrderStatus.
const (
	OrderStatusCancelled OrderStatus = "cancelled"
	OrderStatusExpired   OrderStatus = "expired"
	OrderStatusPaid      OrderStatus = "paid"
	OrderStatusPending   OrderStatus = "pending"
)

// Valid indicates whether the value is a known member of the OrderStatus enum.
func (e OrderStatus) Valid() bool {
	switch e {
	case OrderStatusCancelled:
		return true
	case OrderStatusExpired:
		return true
	case OrderStatusPaid:
		return true
	case OrderStatusPending:
		return true
	default:
		return false
	}
}

// Defines values for OutboxInspectionStatus.
const (
	OutboxInspectionStatusFailed     OutboxInspectionStatus = "failed"
	OutboxInspectionStatusPending    OutboxInspectionStatus = "pending"
	OutboxInspectionStatusPublished  OutboxInspectionStatus = "published"
	OutboxInspectionStatusPublishing OutboxInspectionStatus = "publishing"
)

// Valid indicates whether the value is a known member of the OutboxInspectionStatus enum.
func (e OutboxInspectionStatus) Valid() bool {
	switch e {
	case OutboxInspectionStatusFailed:
		return true
	case OutboxInspectionStatusPending:
		return true
	case OutboxInspectionStatusPublished:
		return true
	case OutboxInspectionStatusPublishing:
		return true
	default:
		return false
	}
}

// Defines values for WebhookEventStatus.
const (
	WebhookEventStatusFailed     WebhookEventStatus = "failed"
	WebhookEventStatusPending    WebhookEventStatus = "pending"
	WebhookEventStatusProcessed  WebhookEventStatus = "processed"
	WebhookEventStatusProcessing WebhookEventStatus = "processing"
	WebhookEventStatusSkipped    WebhookEventStatus = "skipped"
)

// Valid indicates whether the value is a known member of the WebhookEventStatus enum.
func (e WebhookEventStatus) Valid() bool {
	switch e {
	case WebhookEventStatusFailed:
		return true
	case WebhookEventStatusPending:
		return true
	case WebhookEventStatusProcessed:
		return true
	case WebhookEventStatusProcessing:
		return true
	case WebhookEventStatusSkipped:
		return true
	default:
		return false
	}
}

// Checkout defines model for Checkout.
type Checkout struct {
	// CheckoutUrl URL HTTPS hospedada pela Stripe.
	CheckoutUrl string `json:"checkoutUrl"`

	// ExpiresAt Instante em que a sessao deixa de aceitar pagamento.
	ExpiresAt time.Time `json:"expiresAt"`
}

// CreateOrderRequest defines model for CreateOrderRequest.
type CreateOrderRequest struct {
	// ProductId Identificador de um produto conhecido pelo servidor.
	ProductId string `json:"productId"`

	// Quantity Quantidade de unidades do produto.
	Quantity int `json:"quantity"`
}

// Error defines model for Error.
type Error struct {
	// Code Codigo estavel do erro, adequado para tratamento programatico.
	Code string `json:"code"`

	// CorrelationId Identificador de correlacao da requisicao, igual ao header X-Correlation-ID.
	CorrelationId string `json:"correlationId"`

	// Message Descricao legivel do erro, sem dados sensiveis.
	Message string `json:"message"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Checks  map[string]HealthResponseChecks `json:"checks"`
	Service string                          `json:"service"`
	Status  HealthResponseStatus            `json:"status"`
	Version string                          `json:"version"`
}

// HealthResponseChecks defines model for HealthResponse.Checks.
type HealthResponseChecks string

// HealthResponseStatus defines model for HealthResponse.Status.
type HealthResponseStatus string

// Order defines model for Order.
type Order struct {
	// Amount Valor total na menor unidade da moeda, calculado no servidor.
	Amount int64 `json:"amount"`

	// Currency Codigo ISO 4217 da moeda.
	Currency string `json:"currency"`

	// Id Identificador publico opaco e nao sequencial.
	Id string `json:"id"`

	// Status Estado comercial do pedido.
	Status OrderStatus `json:"status"`
}

// OrderStatus Estado comercial do pedido.
type OrderStatus string

// OutboxInspection defines model for OutboxInspection.
type OutboxInspection struct {
	Attempts      int                    `json:"attempts"`
	Id            string                 `json:"id"`
	LastError     *string                `json:"lastError,omitempty"`
	NextAttemptAt time.Time              `json:"nextAttemptAt"`
	PublishedAt   *time.Time             `json:"publishedAt,omitempty"`
	Status        OutboxInspectionStatus `json:"status"`
}

// OutboxInspectionStatus defines model for OutboxInspection.Status.
type OutboxInspectionStatus string

// WebhookEventInspection defines model for WebhookEventInspection.
type WebhookEventInspection struct {
	Attempts        int                `json:"attempts"`
	EventType       string             `json:"eventType"`
	Id              string             `json:"id"`
	LastError       *string            `json:"lastError,omitempty"`
	LastReplayedAt  *time.Time         `json:"lastReplayedAt,omitempty"`
	Outbox          *OutboxInspection  `json:"outbox,omitempty"`
	ProcessedAt     *time.Time         `json:"processedAt,omitempty"`
	Provider        string             `json:"provider"`
	ProviderEventId string             `json:"providerEventId"`
	ReceivedAt      time.Time          `json:"receivedAt"`
	ReplayCount     int                `json:"replayCount"`
	Status          WebhookEventStatus `json:"status"`
	UpdatedAt       time.Time          `json:"updatedAt"`
}

// WebhookEventList defines model for WebhookEventList.
type WebhookEventList struct {
	Items []WebhookEventInspection `json:"items"`
}

// WebhookEventStatus defines model for WebhookEventStatus.
type WebhookEventStatus string

// IdempotencyKey defines model for IdempotencyKey.
type IdempotencyKey = string

// OrderId defines model for OrderId.
type OrderId = string

// WebhookEventId defines model for WebhookEventId.
type WebhookEventId = string

// TooManyRequests defines model for TooManyRequests.
type TooManyRequests = Error

// CreateOrderParams defines parameters for CreateOrder.
type CreateOrderParams struct {
	// IdempotencyKey Chave opaca escolhida pelo cliente que identifica esta operacao. Deve
	// ter entre 1 e 255 caracteres. Reenviar a mesma chave nao cria um
	// segundo pedido.
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// CreateCheckoutParams defines parameters for CreateCheckout.
type CreateCheckoutParams struct {
	// IdempotencyKey Chave opaca escolhida pelo cliente que identifica esta operacao. Deve
	// ter entre 1 e 255 caracteres. Reenviar a mesma chave nao cria um
	// segundo pedido.
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// ListWebhookEventsParams defines parameters for ListWebhookEvents.
type ListWebhookEventsParams struct {
	Status *WebhookEventStatus `form:"status,omitempty" json:"status,omitempty"`
	Limit  *int                `form:"limit,omitempty" json:"limit,omitempty"`
}

// ReceiveStripeWebhookParams defines parameters for ReceiveStripeWebhook.
type ReceiveStripeWebhookParams struct {
	// StripeSignature Assinatura do corpo bruto. Declarado como opcional para que a
	// ausencia seja tratada pelo mesmo caminho de uma assinatura
	// invalida, com o codigo de erro invalid_signature.
	StripeSignature *string `json:"Stripe-Signature,omitempty"`
}

// CreateOrderJSONRequestBody defines body for CreateOrder for application/json ContentType.
type CreateOrderJSONRequestBody = CreateOrderRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetHealth Retorna a disponibilidade do processo e de suas dependencias.
	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// CreateOrder Cria um pedido a partir de um produto conhecido pelo servidor.
	// (POST /v1/orders)
	CreateOrder(w http.ResponseWriter, r *http.Request, params CreateOrderParams)
	// GetOrder Retorna o estado local atual de um pedido.
	// (GET /v1/orders/{orderId})
	GetOrder(w http.ResponseWriter, r *http.Request, orderId OrderId)
	// CreateCheckout Cria ou recupera uma sessao hospedada de pagamento.
	// (POST /v1/orders/{orderId}/checkout)
	CreateCheckout(w http.ResponseWriter, r *http.Request, orderId OrderId, params CreateCheckoutParams)
	// ListWebhookEvents Lista metadados operacionais da inbox e da outbox.
	// (GET /v1/webhook-events)
	ListWebhookEvents(w http.ResponseWriter, r *http.Request, params ListWebhookEventsParams)
	// ReprocessWebhookEvent Reenfileira atomicamente um evento ou publicacao com falha.
	// (POST /v1/webhook-events/{webhookEventId}/reprocess)
	ReprocessWebhookEvent(w http.ResponseWriter, r *http.Request, webhookEventId WebhookEventId)
	// ReceiveStripeWebhook Recebe um evento assinado pela Stripe.
	// (POST /v1/webhooks/stripe)
	ReceiveStripeWebhook(w http.ResponseWriter, r *http.Request, params ReceiveStripeWebhookParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateOrder operation middleware
func (siw *ServerInterfaceWrapper) CreateOrder(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateOrderParams

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateOrder(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetOrder operation middleware
func (siw *ServerInterfaceWrapper) GetOrder(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "orderId" -------------
	var orderId OrderId

	err = runtime.BindStyledParameterWithOptions("simple", "orderId", r.PathValue("orderId"), &orderId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "orderId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetOrder(w, r, orderId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateCheckout operation middleware
func (siw *ServerInterfaceWrapper) CreateCheckout(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "orderId" -------------
	var orderId OrderId

	err = runtime.BindStyledParameterWithOptions("simple", "orderId", r.PathValue("orderId"), &orderId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "orderId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateCheckoutParams

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateCheckout(w, r, orderId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListWebhookEvents operation middleware
func (siw *ServerInterfaceWrapper) ListWebhookEvents(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListWebhookEventsParams

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", r.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "status"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListWebhookEvents(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ReprocessWebhookEvent operation middleware
func (siw *ServerInterfaceWrapper) ReprocessWebhookEvent(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "webhookEventId" -------------
	var webhookEventId WebhookEventId

	err = runtime.BindStyledParameterWithOptions("simple", "webhookEventId", r.PathValue("webhookEventId"), &webhookEventId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "webhookEventId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ReprocessWebhookEvent(w, r, webhookEventId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ReceiveStripeWebhook operation middleware
func (siw *ServerInterfaceWrapper) ReceiveStripeWebhook(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ReceiveStripeWebhookParams

	headers := r.Header

	// ------------- Optional header parameter "Stripe-Signature" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Stripe-Signature")]; found {
		var StripeSignature string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Stripe-Signature", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Stripe-Signature", valueList[0], &StripeSignature, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Stripe-Signature", Err: err})
			return
		}

		params.StripeSignature = &StripeSignature

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ReceiveStripeWebhook(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/health", wrapper.GetHealth)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/orders", wrapper.CreateOrder)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/orders/{orderId}", wrapper.GetOrder)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/orders/{orderId}/checkout", wrapper.CreateCheckout)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/webhook-events", wrapper.ListWebhookEvents)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/webhook-events/{webhookEventId}/reprocess", wrapper.ReprocessWebhookEvent)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/webhooks/stripe", wrapper.ReceiveStripeWebhook)

	return m
}

type TooManyRequestsResponseHeaders struct {
	RetryAfter     int
	XCorrelationID string
}
type TooManyRequestsJSONResponse struct {
	Body Error

	Headers TooManyRequestsResponseHeaders
}

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200ResponseHeaders struct {
	XCorrelationID string
}

type GetHealth200JSONResponse struct {
	Body    HealthResponse
	Headers GetHealth200ResponseHeaders
}

func (response GetHealth200JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Correlation-ID", fmt.Sprint(response.Headers.XCorrelationID))
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealth429JSONResponse struct{ TooManyRequestsJSONResponse }

func (response GetHealth429JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Retry-After", fmt.Sprint(response.Headers.RetryAfter))
	w.Header().Set("X-Correlation-ID", fmt.Sprint(response.Headers.XCorrelationID))
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealth503ResponseHeaders struct {
	XCorrelationID string
}

type GetHealth503JSONResponse struct {
	Body    HealthResponse
	Headers GetHealth503ResponseHeaders
}

func (response GetHealth503JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Correlation-ID", fmt.Sprint(response.Headers.XCorrelationID))
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type CreateOrderRequestObject struct {
	Params CreateOrderParams
	Body   *CreateOrderJSONRequestBody
}

type CreateOrderResponseObject interface {
	VisitCreateOrderResponse(w http.ResponseWriter) error
}

type CreateOrder201ResponseHeaders struct {
	XCorrelationID string
}

type CreateOrder201JSONResponse struct {
	Body    Order
	Headers CreateOrder201ResponseHeaders
}

func (response CreateOrder201JSONResponse) VisitCreateOrderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Correlation-ID", fmt.Sprint(response.Headers.XCorrelationID))
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateOrder400ResponseHeaders struct {
	XCorrelationID string
}

type CreateOrder400JSONResponse struct {
	Body    Error
	Headers CreateOrder400ResponseHeaders
}

func (response CreateOrder400JSONResponse) VisitCreateOrderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Correlation-ID", fmt.Sprint(response.Headers.XCorrelationID))
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateOrder401ResponseHeaders struct {
	XCorrelationID string
}

type CreateOrder401JSONResponse struct {
	Body    Error
	Headers CreateOrder401ResponseHeaders
}

func (response CreateOrder401JSONResponse) VisitCreateOrderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Correlation-ID", fmt.Sprint(response.Headers.XCorrelationID))
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateOrder404ResponseHeaders struct {
	XCorrelationID string
}

type CreateOrder404JSONResponse struct {
	Body    Error
	Headers CreateOrder404ResponseHeaders
}

func (response CreateOrder404JSONResponse) VisitCreateOrderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Correlation-ID", fmt.Sprint(response.Headers.XCorrelationID))
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type CreateOrder409ResponseHeaders struct {
	XCorrelationID string
}

type CreateOrder409JSONResponse struct {
	Body    Error
	Headers CreateOrder409ResponseHeaders
}

func (response CreateOrder409JSONResponse) VisitCreateOrderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Correlation-ID", fmt.Sprint(response.Headers.XCorrelationID))
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type CreateOrder413ResponseHeaders struct {
	XCorrelationID string
}

type CreateOrder413JSONResponse struct {
	Body    Error
	Headers CreateOrder413ResponseHeaders
}

func (response CreateOrder413JSONResponse) VisitCreateOrderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Correlation-ID", fmt.Sprint(response.Headers.XCorrelationID))
	w.WriteHeader(413)
	_, err := buf.WriteTo(w)
	return err
}

type CreateOrder429JSONResponse struct{ TooManyRequestsJSONResponse }

func (response CreateOrder429JSONResponse) VisitCreateOrderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Retry-After", fmt.Sprint(response.Headers.RetryAfter))
	w.Header().Set("X-Correlation-ID", fmt.Sprint(response.Headers.XCorrelationID))
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type CreateOrder500ResponseHeaders struct {
	XCorrelationID string
}

type CreateOrder500JSONResponse struct {
	Body    Error
	Headers CreateOrder500ResponseHeaders
}

func (response CreateOrder500JSONResponse) VisitCreateOrderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Correlation-ID", fmt.Sprint(response.Headers.XCorrelationID))
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetOrderRequestObject struct {
	OrderId OrderId `json:"orderId"`
}

type GetOrderResponseObject interface {
	VisitGetOrderResponse(w http.ResponseWriter) error
}

type GetOrder200ResponseHeaders struct {
	XCorrelationID string
}

type GetOrder200JSONResponse struct {
	Body    Order
	Headers GetOrder200ResponseHeaders
}

func (response GetOrder200JSONResponse) VisitGetOrderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Correlation-ID", fmt.Sprint(response.Headers.XCorrelationID))
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetOrder401ResponseHeaders struct {
	XCorrelationID string
}

type GetOrder401JSONResponse struct {
	Body    Error
	Headers GetOrder401ResponseHeaders
}

func (response GetOrder401JSONResponse) VisitGetOrderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Correlation-ID", fmt.Sprint(response.Headers.XCorrelationID))
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetOrder404ResponseHeaders struct {
	XCorrelationID string
}

type GetOrder404JSONResponse struct {
	Body    Error
	Headers GetOrder404ResponseHeaders
}

func (response GetOrder404JSONResponse) VisitGetOrderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Correlation-ID", fmt.Sprint(response.Headers.XCorrelationID))
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetOrder429JSONResponse struct{ TooManyRequestsJSONResponse }

func (response GetOrder429JSONResponse) VisitGetOrderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Retry-After", fmt.Sprint(response.Headers.RetryAfter))
	w.Header().Set("X-Correlation-ID", fmt.Sprint(response.Headers.XCorrelationID))
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type GetOrder500ResponseHeaders struct {
	XCorrelationID string
}

type GetOrder500JSONResponse struct {
	Body    Error
	Headers GetOrder500ResponseHeaders
}

func (response GetOrder500JSONResponse) VisitGetOrderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Correlation-ID", fmt.Sprint(response.Headers.XCorrelationID))
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type CreateCheckoutRequestObject struct {
	OrderId OrderId `json:"orderId"`
	Params  CreateCheckoutParams
}

type CreateCheckoutResponseObject interface {
	VisitCreateCheckoutResponse(w http.ResponseWriter) error
}

type CreateCheckout201ResponseHeaders struct {
	XCorrelationID string
}

type CreateCheckout201JSONResponse struct {
	Body    Checkout
	Headers CreateCheckout201ResponseHeaders
}

func (response CreateCheckout201JSONResponse) VisitCreateCheckoutResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Correlation-ID", fmt.Sprint(response.Headers.XCorrelationID))
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateCheckout400ResponseHeaders struct {
	XCorrelationID string
}

type CreateCheckout400JSONResponse struct {
	Body    Error
	Headers CreateCheckout400ResponseHeaders
}

func (response CreateCheckout400JSONResponse) VisitCreateCheckoutResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Correlation-ID", fmt.Sprint(response.Headers.XCorrelationID))
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateCheckout401ResponseHeaders struct {
	XCorrelationID string
}

type CreateCheckout401JSONResponse struct {
	Body    Error
	Headers CreateCheckout401ResponseHeaders
}

func (response CreateCheckout401JSONResponse) VisitCreateCheckoutResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Correlation-ID", fmt.Sprint(response.Headers.XCorrelationID))
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateCheckout404ResponseHeaders struct {
	XCorrelationID string
}

type CreateCheckout404JSONResponse struct {
	Body    Error
	Headers CreateCheckout404ResponseHeaders
}

func (response CreateCheckout404JSONResponse) VisitCreateCheckoutResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Correlation-ID", fmt.Sprint(response.Headers.XCorrelationID))
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type CreateCheckout409ResponseHeaders struct {
	XCorrelationID string
}

type CreateCheckout409JSONResponse struct {
	Body    Error
	Headers CreateCheckout409ResponseHeaders
}

func (response CreateCheckout409JSONResponse) VisitCreateCheckoutResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Correlation-ID", fmt.Sprint(response.Headers.XCorrelationID))
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type CreateCheckout429JSONResponse struct{ TooManyRequestsJSONResponse }

func (response CreateCheckout429JSONResponse) VisitCreateCheckoutResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Retry-After", fmt.Sprint(response.Headers.RetryAfter))
	w.Header().Set("X-Correlation-ID", fmt.Sprint(response.Headers.XCorrelationID))
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type CreateCheckout500ResponseHeaders struct {
	XCorrelationID string
}

type CreateCheckout500JSONResponse struct {
	Body    Error
	Headers CreateCheckout500ResponseHeaders
}

func (response CreateCheckout500JSONResponse) VisitCreateCheckoutResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Correlation-ID", fmt.Sprint(response.Headers.XCorrelationID))
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type CreateCheckout502ResponseHeaders struct {
	XCorrelationID string
}

type CreateCheckout502JSONResponse struct {
	Body    Error
	Headers CreateCheckout502ResponseHeaders
}

func (response CreateCheckout502JSONResponse) VisitCreateCheckoutResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Correlation-ID", fmt.Sprint(response.Headers.XCorrelationID))
	w.WriteHeader(502)
	_, err := buf.WriteTo(w)
	return err
}

type ListWebhookEventsRequestObject struct {
	Params ListWebhookEventsParams
}

type ListWebhookEventsResponseObject interface {
	VisitListWebhookEventsResponse(w http.ResponseWriter) error
}

type ListWebhookEvents200ResponseHeaders struct {
	XCorrelationID string
}

type ListWebhookEvents200JSONResponse struct {
	Body    WebhookEventList
	Headers ListWebhookEvents200ResponseHeaders
}

func (response ListWebhookEvents200JSONResponse) VisitListWebhookEventsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Correlation-ID", fmt.Sprint(response.Headers.XCorrelationID))
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListWebhookEvents400ResponseHeaders struct {
	XCorrelationID string
}

type ListWebhookEvents400JSONResponse struct {
	Body    Error
	Headers ListWebhookEvents400ResponseHeaders
}

func (response ListWebhookEvents400JSONResponse) VisitListWebhookEventsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Correlation-ID", fmt.Sprint(response.Headers.XCorrelationID))
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListWebhookEvents401ResponseHeaders struct {
	XCorrelationID string
}

type ListWebhookEvents401JSONResponse struct {
	Body    Error
	Headers ListWebhookEvents401ResponseHeaders
}

func (response ListWebhookEvents401JSONResponse) VisitListWebhookEventsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Correlation-ID", fmt.Sprint(response.Headers.XCorrelationID))
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListWebhookEvents429JSONResponse struct{ TooManyRequestsJSONResponse }

func (response ListWebhookEvents429JSONResponse) VisitListWebhookEventsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Retry-After", fmt.Sprint(response.Headers.RetryAfter))
	w.Header().Set("X-Correlation-ID", fmt.Sprint(response.Headers.XCorrelationID))
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type ListWebhookEvents500ResponseHeaders struct {
	XCorrelationID string
}

type ListWebhookEvents500JSONResponse struct {
	Body    Error
	Headers ListWebhookEvents500ResponseHeaders
}

func (response ListWebhookEvents500JSONResponse) VisitListWebhookEventsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Correlation-ID", fmt.Sprint(response.Headers.XCorrelationID))
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ReprocessWebhookEventRequestObject struct {
	WebhookEventId WebhookEventId `json:"webhookEventId"`
}

type ReprocessWebhookEventResponseObject interface {
	VisitReprocessWebhookEventResponse(w http.ResponseWriter) error
}

type ReprocessWebhookEvent202ResponseHeaders struct {
	XCorrelationID string
}

type ReprocessWebhookEvent202JSONResponse struct {
	Body    WebhookEventInspection
	Headers ReprocessWebhookEvent202ResponseHeaders
}

func (response ReprocessWebhookEvent202JSONResponse) VisitReprocessWebhookEventResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Correlation-ID", fmt.Sprint(response.Headers.XCorrelationID))
	w.WriteHeader(202)
	_, err := buf.WriteTo(w)
	return err
}

type ReprocessWebhookEvent401ResponseHeaders struct {
	XCorrelationID string
}

type ReprocessWebhookEvent401JSONResponse struct {
	Body    Error
	Headers ReprocessWebhookEvent401ResponseHeaders
}

func (response ReprocessWebhookEvent401JSONResponse) VisitReprocessWebhookEventResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Correlation-ID", fmt.Sprint(response.Headers.XCorrelationID))
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ReprocessWebhookEvent404ResponseHeaders struct {
	XCorrelationID string
}

type ReprocessWebhookEvent404JSONResponse struct {
	Body    Error
	Headers ReprocessWebhookEvent404ResponseHeaders
}

func (response ReprocessWebhookEvent404JSONResponse) VisitReprocessWebhookEventResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Correlation-ID", fmt.Sprint(response.Headers.XCorrelationID))
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ReprocessWebhookEvent409ResponseHeaders struct {
	XCorrelationID string
}

type ReprocessWebhookEvent409JSONResponse struct {
	Body    Error
	Headers ReprocessWebhookEvent409ResponseHeaders
}

func (response ReprocessWebhookEvent409JSONResponse) VisitReprocessWebhookEventResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Correlation-ID", fmt.Sprint(response.Headers.XCorrelationID))
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type ReprocessWebhookEvent429JSONResponse struct{ TooManyRequestsJSONResponse }

func (response ReprocessWebhookEvent429JSONResponse) VisitReprocessWebhookEventResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Retry-After", fmt.Sprint(response.Headers.RetryAfter))
	w.Header().Set("X-Correlation-ID", fmt.Sprint(response.Headers.XCorrelationID))
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type ReprocessWebhookEvent500ResponseHeaders struct {
	XCorrelationID string
}

type ReprocessWebhookEvent500JSONResponse struct {
	Body    Error
	Headers ReprocessWebhookEvent500ResponseHeaders
}

func (response ReprocessWebhookEvent500JSONResponse) VisitReprocessWebhookEventResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Correlation-ID", fmt.Sprint(response.Headers.XCorrelationID))
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ReceiveStripeWebhookRequestObject struct {
	Params ReceiveStripeWebhookParams
	Body   io.Reader
}

type ReceiveStripeWebhookResponseObject interface {
	VisitReceiveStripeWebhookResponse(w http.ResponseWriter) error
}

type ReceiveStripeWebhook200ResponseHeaders struct {
	XCorrelationID string
}

type ReceiveStripeWebhook200Response struct {
	Headers ReceiveStripeWebhook200ResponseHeaders
}

func (response ReceiveStripeWebhook200Response) VisitReceiveStripeWebhookResponse(w http.ResponseWriter) error {
	w.Header().Set("X-Correlation-ID", fmt.Sprint(response.Headers.XCorrelationID))
	w.WriteHeader(200)
	return nil
}

type ReceiveStripeWebhook202ResponseHeaders struct {
	XCorrelationID string
}

type ReceiveStripeWebhook202Response struct {
	Headers ReceiveStripeWebhook202ResponseHeaders
}

func (response ReceiveStripeWebhook202Response) VisitReceiveStripeWebhookResponse(w http.ResponseWriter) error {
	w.Header().Set("X-Correlation-ID", fmt.Sprint(response.Headers.XCorrelationID))
	w.WriteHeader(202)
	return nil
}

type ReceiveStripeWebhook400ResponseHeaders struct {
	XCorrelationID string
}

type ReceiveStripeWebhook400JSONResponse struct {
	Body    Error
	Headers ReceiveStripeWebhook400ResponseHeaders
}

func (response ReceiveStripeWebhook400JSONResponse) VisitReceiveStripeWebhookResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Correlation-ID", fmt.Sprint(response.Headers.XCorrelationID))
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ReceiveStripeWebhook429JSONResponse struct{ TooManyRequestsJSONResponse }

func (response ReceiveStripeWebhook429JSONResponse) VisitReceiveStripeWebhookResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Retry-After", fmt.Sprint(response.Headers.RetryAfter))
	w.Header().Set("X-Correlation-ID", fmt.Sprint(response.Headers.XCorrelationID))
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type ReceiveStripeWebhook500ResponseHeaders struct {
	XCorrelationID string
}

type ReceiveStripeWebhook500JSONResponse struct {
	Body    Error
	Headers ReceiveStripeWebhook500ResponseHeaders
}

func (response ReceiveStripeWebhook500JSONResponse) VisitReceiveStripeWebhookResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("X-Correlation-ID", fmt.Sprint(response.Headers.XCorrelationID))
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// GetHealth Retorna a disponibilidade do processo e de suas dependencias.
	// (GET /health)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
	// CreateOrder Cria um pedido a partir de um produto conhecido pelo servidor.
	// (POST /v1/orders)
	CreateOrder(ctx context.Context, request CreateOrderRequestObject) (CreateOrderResponseObject, error)
	// GetOrder Retorna o estado local atual de um pedido.
	// (GET /v1/orders/{orderId})
	GetOrder(ctx context.Context, request GetOrderRequestObject) (GetOrderResponseObject, error)
	// CreateCheckout Cria ou recupera uma sessao hospedada de pagamento.
	// (POST /v1/orders/{orderId}/checkout)
	CreateCheckout(ctx context.Context, request CreateCheckoutRequestObject) (CreateCheckoutResponseObject, error)
	// ListWebhookEvents Lista metadados operacionais da inbox e da outbox.
	// (GET /v1/webhook-events)
	ListWebhookEvents(ctx context.Context, request ListWebhookEventsRequestObject) (ListWebhookEventsResponseObject, error)
	// ReprocessWebhookEvent Reenfileira atomicamente um evento ou publicacao com falha.
	// (POST /v1/webhook-events/{webhookEventId}/reprocess)
	ReprocessWebhookEvent(ctx context.Context, request ReprocessWebhookEventRequestObject) (ReprocessWebhookEventResponseObject, error)
	// ReceiveStripeWebhook Recebe um evento assinado pela Stripe.
	// (POST /v1/webhooks/stripe)
	ReceiveStripeWebhook(ctx context.Context, request ReceiveStripeWebhookRequestObject) (ReceiveStripeWebhookResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(w http.ResponseWriter, r *http.Request) {
	var request GetHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateOrder operation middleware
func (sh *strictHandler) CreateOrder(w http.ResponseWriter, r *http.Request, params CreateOrderParams) {
	var request CreateOrderRequestObject

	request.Params = params

	var body CreateOrderJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateOrder(ctx, request.(CreateOrderRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateOrder")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateOrderResponseObject); ok {
		if err := validResponse.VisitCreateOrderResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetOrder operation middleware
func (sh *strictHandler) GetOrder(w http.ResponseWriter, r *http.Request, orderId OrderId) {
	var request GetOrderRequestObject

	request.OrderId = orderId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetOrder(ctx, request.(GetOrderRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetOrder")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetOrderResponseObject); ok {
		if err := validResponse.VisitGetOrderResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateCheckout operation middleware
func (sh *strictHandler) CreateCheckout(w http.ResponseWriter, r *http.Request, orderId OrderId, params CreateCheckoutParams) {
	var request CreateCheckoutRequestObject

	request.OrderId = orderId
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateCheckout(ctx, request.(CreateCheckoutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateCheckout")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateCheckoutResponseObject); ok {
		if err := validResponse.VisitCreateCheckoutResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListWebhookEvents operation middleware
func (sh *strictHandler) ListWebhookEvents(w http.ResponseWriter, r *http.Request, params ListWebhookEventsParams) {
	var request ListWebhookEventsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListWebhookEvents(ctx, request.(ListWebhookEventsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListWebhookEvents")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListWebhookEventsResponseObject); ok {
		if err := validResponse.VisitListWebhookEventsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ReprocessWebhookEvent operation middleware
func (sh *strictHandler) ReprocessWebhookEvent(w http.ResponseWriter, r *http.Request, webhookEventId WebhookEventId) {
	var request ReprocessWebhookEventRequestObject

	request.WebhookEventId = webhookEventId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ReprocessWebhookEvent(ctx, request.(ReprocessWebhookEventRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ReprocessWebhookEvent")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ReprocessWebhookEventResponseObject); ok {
		if err := validResponse.VisitReprocessWebhookEventResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ReceiveStripeWebhook operation middleware
func (sh *strictHandler) ReceiveStripeWebhook(w http.ResponseWriter, r *http.Request, params ReceiveStripeWebhookParams) {
	var request ReceiveStripeWebhookRequestObject

	request.Params = params

	request.Body = r.Body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ReceiveStripeWebhook(ctx, request.(ReceiveStripeWebhookRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ReceiveStripeWebhook")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ReceiveStripeWebhookResponseObject); ok {
		if err := validResponse.VisitReceiveStripeWebhookResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Hxtc9s4kv9X6eJ/X9K2JD/E0b/2hceTvfFdLs7Gyd1WRblUi2hJSEiAAUCNNSl/96sGQIqU6AeN7Z29",
	"3fiVLFFAP/76AQ19TzJdlFqRcjYZf08WhIKMf3mujaEcndTqQvAbgmxmZMlvJOPkQpByciYzFNqALjHT",
	"8K0iyMLXMqkVAoIhW2rrEFBbyPXcguA3v1XSygz1fpIm/j9DIhk7U1Ga2GxBBfKOBV6/JjV3i2Q8HJ2m",
	"SSFV83+auFVJyTixzkg1T25u0uQdObM6mzky2/Re0bxSQltAIFuSQQOoHFkQBIZKctLAJmV0jUWZUzI+",
	"GdxJplSyqIo2UVI5mpNJbpisEg0W5KJcLwQVpXakstV/0Gqb0PMFLskLlCnNdL6QAqGkXEOWS1KOvJxl",
	"I38glq9mnphu+JmWNFGODJByhmAIBKPjY8jQYObIkN2Hd0RqKVkGUJAtEDK/q0INmZEIVTFRNkgMShJS",
	"6P2JakskOc2Gs+PZiPZe4uF07ygbib1TejHbG+JoepgdiWM6mSVpIpmlYFVJmigsKBm3RbDHMnigDYyO",
	"j++3gUsjyNxvsGU1zWWmo+GuuezwqI34fDgbHQ+OaHA0O305HIrDlzjIBoeDYzodZYeHg2HNY4luseZQ",
	"Ryru4qxE58jwd/+HN/o42HuJe7NP3w9HN39K+lj7b5outP76aknKPdQlBXorQIGgEKSa6usuj7R0v5PH",
	"X7vkPJBV3u8+Vm94LVtqZcm7zHut/xPV6h19q8gGoMq0cqQcv8SyzGXmgergi2VJfK/5848adPRaFtKR",
	"l9kS84rCEoJ35Y8/5/HzNMm6sJeczIZilA3waHpKR7OT7KUY0mh2iEfT4+xEvKAkTQqyFue8ltMaClQr",
	"MDWpnpm1IP5kaJaMk/93sIbdg/CpPXhljI6I0dVrID4AVYAnTRboOgsmC5cQHAw8/u15AASpZtoUmAKt",
	"Xdmm8K1C9umqQFB6icBCRCeXCKUWBJYMzEg63IezNXYr1BNlaEk58gI5BHHBTEtAJ9W8wYdW/GgRcxvn",
	"8emDFm7fpMnf9lqhZ+/i5/u+3Q1UNy2Jhzi2oOyrrryplIZh0slgGFn85IPJt53pw7vX8Mv792+vYKFt",
	"SQIDCCNcOSNLYifyAnbJOKmM3LZidrJSGrJnrsdVlXXIUE6FR3MEy0akQZC8RlY1ZqwGAyXOsSDldGdH",
	"gY72nCyoFyjWjvixw2SbpE/NF/X0C2WOCT43hI48gkZf2xZaabSosgfgjyCoCvCPOw2ZVgvKpAfaXLOd",
	"LaXQhpnaKcqnCVuwk64ncv7VfyJQeF+plH9pPbgHKuJuMVgPBoP07tjdleSa8xYRfWIMjrxtbh5vtsK9",
	"FnKufQxfUs7EkjE6BRT0rUKmHQ2CM+iCGTAvc4MFOpl5hrYElO2SuIl1xoa6m5ulIOfs7KhrfNn0zN7t",
	"GzTc3Phn/x9vk9Ncdpi1VIBAzs4sKSuXJO3+/ZbN8lzvt8l4n2Z+Iczd4l2MLbcggn+FQkheCPO3nSdI",
	"sbF8TKoySROhf1XJpy06ezb29p75Hbcetg5d1Vlcf03SpFK4RJnjNKfePZZkrAzR7m45xfXXRKy/m9Yc",
	"9wnL48C2jLDQleqBtP/CXBtw2mHOqUZBSpvaCdmwCk0CU8gwz6qcDVt1YaDBNqncyVGy7Y5pklXGcNJ4",
	"qxddXF3C0Wj4otmv10LljtlhyIstI6LKJOa9i661eFeM9zK9Co9u6kmKpFkmrcXcYvpWHV01W3d5emUd",
	"yznTBRmmeyPNjcZWkhLMA9cpnoQMVUZ5TqKJF6LXAC8rN9XXF8qWlLloiRum4hwVZUjYGqAd9Gk2qGRr",
	"ixyta9B061NF1+4sbBFi7EPCY5p45doFiV2+tO2kLbmFBTv/eOnNUOa9wrtb87XUNjnsM4BOTfAkqiBe",
	"6r1/+/ttvrOjovjTd1TmuNpN6Npb2L0+tWmHrGOjM7J2t+1Ko5cyYt6tH7aqr61nDGUkl7ttarxczmtM",
	"vVs3DwOZtk3UWJMmVcl07EBbn5E2ItoWSNty+q25JZ42OV0Z3Gfkr2VfViodFd0XDxVQ127i1mgMrrYl",
	"4Ne+j8Cru5AimGXnnzZSpIn9KsvyNsywlFVGutUV8xEZZ+MwPuc5K+UdDSVLmSGHHAOmmH0lJSB+N8bf",
	"3k7N3/bO3l7EHk0tm7CNL7O4yNze8Ozthc8Yc7KxvTYj40NnSGbjvr6KFdStcJx0vi3xFlf8noWftMzJ",
	"lDk6grO3F63kZZwM9of7Aw8UJSksZTJODv1bqW9VeAFxmZhzLfE9mZO3HN8pa+r7fyMXssJko+kwGgwe",
	"0Gh4WGm/kXf21PhvgzH49N5n+SwodpgpGXAGp5gvvIBaFfajC+U0ORq9vO1bjTAONtsvN2lyPDj8Owrn",
	"Q8ElMbtRsCI9NXKOThsZm59SCclf56riqYXU8rtk/PFTmtiqKNCskjG3OLTxbe64/VTmMd/1igwa9dWo",
	"rdC2eQj1Dc4tA8RlbZE2+cT7HSyHB9rUHJTa9qTbl7D0CTdBTHXX2R1Y1Os827YTbfAu6KQBoScqQ4e5",
	"nvsWUt1bjn0jQHYpC03t7Df61lTY/x8UqQW3iSMZ3E7mpL5dQUJsY/gclFeiLPaJuj7Y6jsk3Xb5x35l",
	"rR852Gin33wKmE3W/aTFasdWoaDC49laxR/WLQxWKxVaWRca7Um67iW2uiL1689+sXa/YrhDM7CnFXNz",
	"c7PZY73ZwqzhjhzXsandGK0rPO6QDNpVV/LTu9dJyAEf2huvM5Zmox1kEAyiDyyDmWdGxvom+sKtteUT",
	"g+ZgsKOUJXuJFH9tta4229Dxkc/ReB/bia6tDorKOpgSTMn9SqRgCKgEsGqfpDd9rk2p07pBpCvIsCj1",
	"xikfROa0fQ5l7GrylcLKLbSRv/UfCHQ+f6QaeCVSLpIDjfc+ieh9XieoyadQA1bWo7iuapnjc4j8aGeR",
	"f1X6V/U2IGOf0GvQVNp9nulKPVrycUFQ2kFY8ClkftlEgxgnfcjTQNfSOmLYaWLqM4j95Y5iN1RZErEo",
	"2AKcdeD8/JVWnzOtZrnMHo08rXXhK60Ac0MoVsCkPIkOzmDj/Bi+oD+Kqqw/pNGMQ860e11PrIjh4Y6K",
	"cFq/RjOnXj08LfDHZWCqxQqc1pD7jZ/G+DNG+w1s9+eQBLo+FIwZnz8rO3t78Y9Us+weth0ZhXm/2sJn",
	"n8mL67FOE1cDWgv/kdr6C+YLrozCtItAiLMdBp7LM27atdF5GCOJW7XqjoceCzbFUSiENgqjg+9xxOLm",
	"rsq+LimerbC/L0UlxdsYFPqPynz+uZOMR3IXtaTwmTX1rIj1HDihla1y9/fCirqPEo7BhYZcZ3zw7Pj4",
	"OQJGQ8UWLuzaMagnxG4+3YIoB1l7ZOR3rp3e0rf5YJFDZl5ZufRtTw6dm62ckoyV1snYvYnMw7t6TnGi",
	"wtTeZiLElID2I331t0DQUufL1oiJNnIuFea3d2KakZknacbs3J94YIekJrLHpq/qYRqonwp9Vaz7qkIa",
	"8iOqTeP5j2gRPNJzfwlFt/DDoFHuEnvg+Ufw+VcOPg8qG59EU4YqJ3P5G0cRKjpVWArlml0+8eH5H13F",
	"Z2rABR5F/BGANUgls5Cq16J5eqEcD0bPz5xvmCwpjpo1R33W20GQvaDK93CroglRz+PX2/WJrsBQVrHc",
	"29uvJz63jidj8lEfT67LkjgNvecPwW2rKNmITLzZTGaSACsXWoMihiUhca609YN9cGmhxFWuUdQTjEGK",
	"fhbXeuH5pIlThFIbHiIttaACvD5NHKcTVB/s2L5wz4fp7bNrux3x/bHwt4rMan0qvJ4oe5Bx9M0j3KT9",
	"S/smQmdlQTOscpeMjwfd6c17hjc/PWPZtzWQ0GP5/kNtoUBp/UkuKyH1lj6TOaOeLn0K4lPcINL/o4nI",
	"XyI/Vd0D+pF3/OsVihYoWPyzwjZ7G0JBDgPAhWtP7EbSHzr5Gy7gB07D9Nh95+xd3D743r3VcnNgKB7k",
	"714MbtzXub0mPAtn7fWYB+dOsRAOc0HruxmGSM1kTtLninDWXPuaqCb5AoRcqgUChVKQW4wgRV33SZvC",
	"b+TrxGkl5uRYVs01kIniSDJjMiogMDSX1vmHw5DWPpwvsECBlnXve57+Fl19c6zg0lTxlsqCqLwRCuwN",
	"Pu9qybbltN2sGz0LarfHvm7D7lg6+/Yl85/jikPx2q5+QNs/WEkV9fZPUVJFXigOo3tNecasw22I+BGL",
	"2tjIhVOIRs/ct2x2BHS6kFns6FVF3J59qqU/n/wx6Q+MSvbA+ttmt4+BvVKi1FI5EGSdVOiPWsIVtdSb",
	"C2qw0joqsD3vCW9Q83kpxJu/E9WBhDG/r9VMosoQlv52DizJyFnNCFOg5wb5DQbFILCJClvvXcm5QlcZ",
	"Aqunhjg7mK6cv7WITvuKxp8l7k/URJ29f/Xm/OySSS1ISATO5ccNH2G2DM6DQe3xgDFsmlQ6UYWfVgtO",
	"77E7y9Fg50mdOXJ71hnCwpd2RpfaSseRdKLQWumJZt7vIjoFqpc3W5RM1Ax9abmeuRNkLRmJHJyND6qt",
	"fwPJVLHiwn10nKiWqFMoKuHvbGrD5Z2goDELBGRLzDS/qnGbn+MbmlxVdTjiK1dOFuhH/ZgJoHCpTMTh",
	"vHDVBV3IM2oCRNQQE9lcgIFwA31Gxnh7R+v/DxQU0NYig5SR4eoaTVSoULHUyqEBqdjj0K3HJsOFdd1M",
	"E/LrKGl/0XWiGqGG+5GdK/ugtCkw93uNQXctxs/SNv22iapsc7ku3LInEwSRk4GOdTY5Vj0T2UqKqE4U",
	"IExNisr4zhb5ZCgNF6FsgRO2SmWDQhFiihTufloyWIOEwH144wcra3hvdyAmim0BBItJe4/v/GIBU3vO",
	"YBiKSSDf05DKOlNloR1uyIt4HjsOtYuNYXR9zSGTVQpoJ6pJCG3aGFTdrAt3rWb421oAdW7q1daf7PnZ",
	"/7BdTMS2mw0bafHafGvXg6nhe5zwc20UtfHGStpzxULFifJpDZurpS/xBmX9QwrhgCTDQqqFDidMzHa9",
	"3UTV/hTq9YZnNlFjmnm2z7aGuc1fR3B/Hr4Yvhz4v3Q5/PPx6PgFnp68pBdshiTwcISzGZ6MMpHh4QyP",
	"hxmKF/TiBQ7o+GQ2Oz48EYOMTmk4OBWnU3HbfP4m3HY6J5sXCB48GtvGyW6w7k1R/v3q8k2UntDtS9Jp",
	"F2LWAMJggz7mBIDF+KMWbSUEtTVAhEHEzcWVqVRoVrf9eMDdQ7KDbVbe+CSCjZrMeG3XXxAWyNHHMnQ0",
	"GIKhl+NLJG89E+VkqWseyna+5kUA8bJ8F0B6bs0/QeIWS6b+zFgvdT2h0wNareLSu9JExRIt3j322smM",
	"Vs9C+O+eq12b/x3zVbblI4+a1Ym5GTQLQqarXPhJwylFi32qWbe1O8QqLW1iPZvfTDM4InxBxW4nCByf",
	"BP4YuvqDhq4ua+Dwx1zrrk3j7/Bz01NwWEx9ChCyuxDgJmpzns5PEYUkP607/YqsJcjQhl/yaEd1azn0",
	"waxSPiRy9llqGTI0vf7hDk52DDeEngOD7rwyw/GvVSD1xY3bTlq66/Zefvv4icMcZ4l1TlGZPBknBzzu",
	"8b8DAA==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
