//go:build go1.22

// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// Defines values for HealthResponseChecks.
const (
	Down HealthResponseChecks = "down"
	Up   HealthResponseChecks = "up"
)

// Valid indicates whether the value is a known member of the HealthResponseChecks enum.
func (e HealthResponseChecks) Valid() bool {
	switch e {
	case Down:
		return true
	case Up:
		return true
	default:
		return false
	}
}

// Defines values for HealthResponseStatus.
const (
	Ok          HealthResponseStatus = "ok"
	Unavailable HealthResponseStatus = "unavailable"
)

// Valid indicates whether the value is a known member of the HealthResponseStatus enum.
func (e HealthResponseStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	case Unavailable:
		return true
	default:
		return false
	}
}

// Defines values for OrderStatus.
const (
	Cancelled OrderStatus = "cancelled"
	Expired   OrderStatus = "expired"
	Paid      OrderStatus = "paid"
	Pending   OrderStatus = "pending"
)

// Valid indicates whether the value is a known member of the OrderStatus enum.
func (e OrderStatus) Valid() bool {
	switch e {
	case Cancelled:
		return true
	case Expired:
		return true
	case Paid:
		return true
	case Pending:
		return true
	default:
		return false
	}
}

// Checkout defines model for Checkout.
type Checkout struct {
	// CheckoutUrl URL HTTPS hospedada pela Stripe.
	CheckoutUrl string `json:"checkoutUrl"`

	// ExpiresAt Instante em que a sessao deixa de aceitar pagamento.
	ExpiresAt time.Time `json:"expiresAt"`
}

// CreateOrderRequest defines model for CreateOrderRequest.
type CreateOrderRequest struct {
	// ProductId Identificador de um produto conhecido pelo servidor.
	ProductId string `json:"productId"`

	// Quantity Quantidade de unidades do produto.
	Quantity int `json:"quantity"`
}

// Error defines model for Error.
type Error struct {
	// Code Codigo estavel do erro, adequado para tratamento programatico.
	Code string `json:"code"`

	// CorrelationId Identificador de correlacao da requisicao, igual ao header X-Correlation-ID.
	CorrelationId string `json:"correlationId"`

	// Message Descricao legivel do erro, sem dados sensiveis.
	Message string `json:"message"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Checks  map[string]HealthResponseChecks `json:"checks"`
	Service string                          `json:"service"`
	Status  HealthResponseStatus            `json:"status"`
	Version string                          `json:"version"`
}

// HealthResponseChecks defines model for HealthResponse.Checks.
type HealthResponseChecks string

// HealthResponseStatus defines model for HealthResponse.Status.
type HealthResponseStatus string

// Order defines model for Order.
type Order struct {
	// Amount Valor total na menor unidade da moeda, calculado no servidor.
	Amount int64 `json:"amount"`

	// Currency Codigo ISO 4217 da moeda.
	Currency string `json:"currency"`

	// Id Identificador publico opaco e nao sequencial.
	Id string `json:"id"`

	// Status Estado comercial do pedido.
	Status OrderStatus `json:"status"`
}

// OrderStatus Estado comercial do pedido.
type OrderStatus string

// IdempotencyKey defines model for IdempotencyKey.
type IdempotencyKey = string

// OrderId defines model for OrderId.
type OrderId = string

// CreateOrderParams defines parameters for CreateOrder.
type CreateOrderParams struct {
	// IdempotencyKey Chave opaca escolhida pelo cliente que identifica esta operacao. Deve
	// ter entre 1 e 255 caracteres. Reenviar a mesma chave nao cria um
	// segundo pedido.
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// CreateCheckoutParams defines parameters for CreateCheckout.
type CreateCheckoutParams struct {
	// IdempotencyKey Chave opaca escolhida pelo cliente que identifica esta operacao. Deve
	// ter entre 1 e 255 caracteres. Reenviar a mesma chave nao cria um
	// segundo pedido.
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// ReceiveStripeWebhookParams defines parameters for ReceiveStripeWebhook.
type ReceiveStripeWebhookParams struct {
	// StripeSignature Assinatura do corpo bruto. Declarado como opcional para que a
	// ausencia seja tratada pelo mesmo caminho de uma assinatura
	// invalida, com o codigo de erro invalid_signature.
	StripeSignature *string `json:"Stripe-Signature,omitempty"`
}

// CreateOrderJSONRequestBody defines body for CreateOrder for application/json ContentType.
type CreateOrderJSONRequestBody = CreateOrderRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetHealth Retorna a disponibilidade do processo e de suas dependencias.
	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// CreateOrder Cria um pedido a partir de um produto conhecido pelo servidor.
	// (POST /v1/orders)
	CreateOrder(w http.ResponseWriter, r *http.Request, params CreateOrderParams)
	// GetOrder Retorna o estado local atual de um pedido.
	// (GET /v1/orders/{orderId})
	GetOrder(w http.ResponseWriter, r *http.Request, orderId OrderId)
	// CreateCheckout Cria ou recupera uma sessao hospedada de pagamento.
	// (POST /v1/orders/{orderId}/checkout)
	CreateCheckout(w http.ResponseWriter, r *http.Request, orderId OrderId, params CreateCheckoutParams)
	// ReceiveStripeWebhook Recebe um evento assinado pela Stripe.
	// (POST /v1/webhooks/stripe)
	ReceiveStripeWebhook(w http.ResponseWriter, r *http.Request, params ReceiveStripeWebhookParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateOrder operation middleware
func (siw *ServerInterfaceWrapper) CreateOrder(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateOrderParams

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateOrder(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetOrder operation middleware
func (siw *ServerInterfaceWrapper) GetOrder(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "orderId" -------------
	var orderId OrderId

	err = runtime.BindStyledParameterWithOptions("simple", "orderId", r.PathValue("orderId"), &orderId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "orderId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetOrder(w, r, orderId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateCheckout operation middleware
func (siw *ServerInterfaceWrapper) CreateCheckout(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "orderId" -------------
	var orderId OrderId

	err = runtime.BindStyledParameterWithOptions("simple", "orderId", r.PathValue("orderId"), &orderId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "orderId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateCheckoutParams

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateCheckout(w, r, orderId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ReceiveStripeWebhook operation middleware
func (siw *ServerInterfaceWrapper) ReceiveStripeWebhook(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ReceiveStripeWebhookParams

	headers := r.Header

	// ------------- Optional header parameter "Stripe-Signature" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Stripe-Signature")]; found {
		var StripeSignature string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Stripe-Signature", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Stripe-Signature", valueList[0], &StripeSignature, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Stripe-Signature", Err: err})
			return
		}

		params.StripeSignature = &StripeSignature

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ReceiveStripeWebhook(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/health", wrapper.GetHealth)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/orders", wrapper.CreateOrder)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/orders/{orderId}", wrapper.GetOrder)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/orders/{orderId}/checkout", wrapper.CreateCheckout)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/webhooks/stripe", wrapper.ReceiveStripeWebhook)

	return m
}

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200JSONResponse HealthResponse

func (response GetHealth200JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealth503JSONResponse HealthResponse

func (response GetHealth503JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type CreateOrderRequestObject struct {
	Params CreateOrderParams
	Body   *CreateOrderJSONRequestBody
}

type CreateOrderResponseObject interface {
	VisitCreateOrderResponse(w http.ResponseWriter) error
}

type CreateOrder201JSONResponse Order

func (response CreateOrder201JSONResponse) VisitCreateOrderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateOrder400JSONResponse Error

func (response CreateOrder400JSONResponse) VisitCreateOrderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateOrder401JSONResponse Error

func (response CreateOrder401JSONResponse) VisitCreateOrderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateOrder404JSONResponse Error

func (response CreateOrder404JSONResponse) VisitCreateOrderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type CreateOrder409JSONResponse Error

func (response CreateOrder409JSONResponse) VisitCreateOrderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type CreateOrder413JSONResponse Error

func (response CreateOrder413JSONResponse) VisitCreateOrderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(413)
	_, err := buf.WriteTo(w)
	return err
}

type CreateOrder500JSONResponse Error

func (response CreateOrder500JSONResponse) VisitCreateOrderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetOrderRequestObject struct {
	OrderId OrderId `json:"orderId"`
}

type GetOrderResponseObject interface {
	VisitGetOrderResponse(w http.ResponseWriter) error
}

type GetOrder200JSONResponse Order

func (response GetOrder200JSONResponse) VisitGetOrderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetOrder401JSONResponse Error

func (response GetOrder401JSONResponse) VisitGetOrderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetOrder404JSONResponse Error

func (response GetOrder404JSONResponse) VisitGetOrderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetOrder500JSONResponse Error

func (response GetOrder500JSONResponse) VisitGetOrderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type CreateCheckoutRequestObject struct {
	OrderId OrderId `json:"orderId"`
	Params  CreateCheckoutParams
}

type CreateCheckoutResponseObject interface {
	VisitCreateCheckoutResponse(w http.ResponseWriter) error
}

type CreateCheckout201JSONResponse Checkout

func (response CreateCheckout201JSONResponse) VisitCreateCheckoutResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateCheckout400JSONResponse Error

func (response CreateCheckout400JSONResponse) VisitCreateCheckoutResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateCheckout401JSONResponse Error

func (response CreateCheckout401JSONResponse) VisitCreateCheckoutResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateCheckout404JSONResponse Error

func (response CreateCheckout404JSONResponse) VisitCreateCheckoutResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type CreateCheckout409JSONResponse Error

func (response CreateCheckout409JSONResponse) VisitCreateCheckoutResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type CreateCheckout500JSONResponse Error

func (response CreateCheckout500JSONResponse) VisitCreateCheckoutResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type CreateCheckout502JSONResponse Error

func (response CreateCheckout502JSONResponse) VisitCreateCheckoutResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(502)
	_, err := buf.WriteTo(w)
	return err
}

type ReceiveStripeWebhookRequestObject struct {
	Params ReceiveStripeWebhookParams
	Body   io.Reader
}

type ReceiveStripeWebhookResponseObject interface {
	VisitReceiveStripeWebhookResponse(w http.ResponseWriter) error
}

type ReceiveStripeWebhook200Response struct {
}

func (response ReceiveStripeWebhook200Response) VisitReceiveStripeWebhookResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type ReceiveStripeWebhook202Response struct {
}

func (response ReceiveStripeWebhook202Response) VisitReceiveStripeWebhookResponse(w http.ResponseWriter) error {
	w.WriteHeader(202)
	return nil
}

type ReceiveStripeWebhook400JSONResponse Error

func (response ReceiveStripeWebhook400JSONResponse) VisitReceiveStripeWebhookResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ReceiveStripeWebhook500JSONResponse Error

func (response ReceiveStripeWebhook500JSONResponse) VisitReceiveStripeWebhookResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// GetHealth Retorna a disponibilidade do processo e de suas dependencias.
	// (GET /health)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
	// CreateOrder Cria um pedido a partir de um produto conhecido pelo servidor.
	// (POST /v1/orders)
	CreateOrder(ctx context.Context, request CreateOrderRequestObject) (CreateOrderResponseObject, error)
	// GetOrder Retorna o estado local atual de um pedido.
	// (GET /v1/orders/{orderId})
	GetOrder(ctx context.Context, request GetOrderRequestObject) (GetOrderResponseObject, error)
	// CreateCheckout Cria ou recupera uma sessao hospedada de pagamento.
	// (POST /v1/orders/{orderId}/checkout)
	CreateCheckout(ctx context.Context, request CreateCheckoutRequestObject) (CreateCheckoutResponseObject, error)
	// ReceiveStripeWebhook Recebe um evento assinado pela Stripe.
	// (POST /v1/webhooks/stripe)
	ReceiveStripeWebhook(ctx context.Context, request ReceiveStripeWebhookRequestObject) (ReceiveStripeWebhookResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(w http.ResponseWriter, r *http.Request) {
	var request GetHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateOrder operation middleware
func (sh *strictHandler) CreateOrder(w http.ResponseWriter, r *http.Request, params CreateOrderParams) {
	var request CreateOrderRequestObject

	request.Params = params

	var body CreateOrderJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateOrder(ctx, request.(CreateOrderRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateOrder")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateOrderResponseObject); ok {
		if err := validResponse.VisitCreateOrderResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetOrder operation middleware
func (sh *strictHandler) GetOrder(w http.ResponseWriter, r *http.Request, orderId OrderId) {
	var request GetOrderRequestObject

	request.OrderId = orderId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetOrder(ctx, request.(GetOrderRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetOrder")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetOrderResponseObject); ok {
		if err := validResponse.VisitGetOrderResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateCheckout operation middleware
func (sh *strictHandler) CreateCheckout(w http.ResponseWriter, r *http.Request, orderId OrderId, params CreateCheckoutParams) {
	var request CreateCheckoutRequestObject

	request.OrderId = orderId
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateCheckout(ctx, request.(CreateCheckoutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateCheckout")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateCheckoutResponseObject); ok {
		if err := validResponse.VisitCreateCheckoutResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ReceiveStripeWebhook operation middleware
func (sh *strictHandler) ReceiveStripeWebhook(w http.ResponseWriter, r *http.Request, params ReceiveStripeWebhookParams) {
	var request ReceiveStripeWebhookRequestObject

	request.Params = params

	request.Body = r.Body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ReceiveStripeWebhook(ctx, request.(ReceiveStripeWebhookRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ReceiveStripeWebhook")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ReceiveStripeWebhookResponseObject); ok {
		if err := validResponse.VisitReceiveStripeWebhookResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Fptc9tIcv4rXch9hCSSejVT90Gr3WSVbFk6a51clem4mjNNcmxgGp4ZcK116b+negYAQRKyrbU2SVVO",
	"n0QSmOnuefrpt/mcKS4rtmSDz6afswodlhTIxU/XmsqKA1l1/+90L99o8sqZKhi22TS7WuGagCtUCOQV",
	"FyujESoqGFRhyAaCjzWB0WSDWZj4VEDgihwq5EP4kdY0s4EckA2OYAwEk9NTUOhQBXLkD+EVkV0bdIBQ",
	"ki8RVNzVIoNyBqEuZ9bTsraaoSJtNB/ObJZn9AnLqqBsml2o8eJ0MaGDF3g8PzhRE31wQeeLgzFO5sfq",
	"RJ/S2SLLMyMqrQg1uSzPLJbybs8EB2KDPHP0sTaOdDYNrqY882pFJYpxSvz0C9llWGXTyelpnpXGtp/H",
	"eRbuK1nQB2fsMnt4yLMbp8ld6327XncG0+ygqueFURztzLDRcktHdvrd8WJyOjqh0cni4sV4rI9f4EiN",
	"jkendDFRx8ejcatjhWG10ZAbKb6kWYUhkJN3/0s2ejM6eIEHi7efjycPf8n2VXto340oulqR+sB1iAs5",
	"OfxgKP6iml9eu2LfCK9f/QI///rr7R2s2FekMUEL4S44U5Gov2BXYsimWe3Mvhhinso48pdhwMTWBxSA",
	"UhkxiuDJe2TQZD4haAJUZAI6qHCJJdnAWztqDHQQTEnZ0MluLPlmS8m+SG+7F3n+nlQQga8cYaCIi1f0",
	"sSY/YLTKsa5V+DpuNEFdQnw8MCi2K1Imwqdg8OTWRrMTpXq4HU8uvoLbPPtYow0mDPDB3+IvGjXFzW38",
	"10fIJima3UxZl9l0PBqN4mbNx24rYwMtye1ZcqN5T4ghM/7kHLsBuLGmARJjbZYcmWlNhQhLznEOqOlj",
	"jSI7OoTgMCQYiC5LhyUGo6JCewZS7BwVKOt/0yk1zytBH0LU2BuFnINZ1lgAMiRagr8fXG3WPrj+cXD7",
	"UoC8HND0x/hJtiloabaU9VSCRs0ePFlv1mT84deRLfbc7Ler+NDJ/ExYhNUr8hVbT48wQvwPtTayEBa3",
	"W0+QFbC8yeoqyzPNv9ns7Z6cAxtHvKu4497DPmCotxbnD1me1RbXaAqcFzS4x5qcj4b9/BU7NetvhNi8",
	"m7caDxkr8sC+jbDk2g5Q2n9gwQ4CByzASrC07FonFGCVTBpzUFiouhBg220a6LjN2HB2ku27Y56p2jkJ",
	"hY960fXdDZxMxufdfoMINU+MeSnae2FEqwwWg4tuTvEvjhbZNPuno01uc9TEo6No07v06O45GZ11y+St",
	"mXtKP3pGd93W2zr95IPYWXFJTuTeCd4N2CqyWnTIswqjCAqtoqIg3cULPQDACGpVOxPu70S5BI54WC66",
	"4GVlvpC1eVKOAopIc1QfyGpo3m3gMJgO/f3g8va6SYQaeTBtE6O+sQve3/Dy9joSWEHeC985WpCLJ5m4",
	"tdlXMcWftwJuMCHmN7d4L995+IFNQa4qMBBc3l73fGmajQ7HhyM5Fa7IYmWyaXYcv8pjzhMNdLSKFCT/",
	"Lil6UUxHW7LO/pVCIqmYECWeii9ORqMURGyg5H5YVYVR8dWj9z4xwSZn+hIKd2gw2m7bZreOFXkfo00M",
	"OmIoR4rm5CA4nGOx4kPR9XR0/D8o1+sSQZNANh0gz51ZYmBnmuTeWG3kdYkvh1sozaZv3uaZr8sS3X02",
	"zV5RYGcREJo35qZoyCqqnfSPqYSv0fe3TcEJl17856Y9P5+9lf2O1uOjmNSmdIn9AFfewDqyJUHDUxvX",
	"BI+8IUnfZ0mIgA3GgeaZVRiw4CUfwk1X7ogDuBIBBYAeusQnbvSxS4/+GSzZlVQujRhS4Qgj98M/NDlo",
	"JBBZiVRT2mwjtpc0ZvlWBfdm+LQ3jxztVHgPbxMjkg8/sL7/Blw1FUhDfmX0/s0Rv97knzEnLNn6kGo/",
	"cVwsatpJadv/38XF+snmuFdXfA3HA3n0w8PDboXzsOfh4ydq3FL39PNGmTY8S3o76ofM7IdXv2Qp+H1r",
	"udbGtG6jJ9ggAWKIWhLMpXhOwanxhUcSg4c8OxmNnmgYI8A2+m+9UqEzUErD20feNXjbSx+n2dlirCdq",
	"hCfzCzpZnKkXekyTxTGezE/VmT7v557TDihQ1j7AnGBO4TciC2NAq0FO4ynWSyXEgPWu2FWctwk516Cw",
	"rNhvZ+7QKMe+sd9TgVVbrMOKnfmd9JDxtn7/TsvJSmRDIw50PvIs1oq5hqYuxiMD1j5yJdetmbCx0smT",
	"rfTB8m/2NlHGkJ1aNrEc3i24tt9trGZBsBwgLfgcZrrpaLIJIDEWMNAn4wOJP3bBJlnqxRMt5aj2pJt0",
	"cM8TN0Hg3Qe6f6fYLgqjvtsle+vCB7oHLByhvgcR5VnMdgk77Tl4j7BgA7WP3SIWBw1uk3SL7cbHT7Rd",
	"YP4F3ZIGTfe8JNYsA3PW9xCYoYgbPw/ElDDXDk/RJ0WagKEwpQldwhH7bJe3102C+XT2D+QsFsMWS7+9",
	"oyjp90KsWQ1oo/d3GupfsFghGEu+IicwahrNDno4eugnslepDd382ksSv7UB12WyKWvdyWKPPjct2ocv",
	"FS1t/ven1SxfyyfIyjYONT8h5v2fCy/fKVBjC4t79jgdjf787Qexy9bXRfgCfttCLDVBNUPBCgvAIM3H",
	"BsRd12IPq08tOdqpx8PbR1B+pPoDgz+4dv5I4ffao5BeUXuzjl0GAt6rBSty3vhgmvKvUR5eUUXi1ziz",
	"aRK1G31EEuA4pmrfAk1rLta9AQM7szQWi8dLuW5g8izV3JMLnG8ssVohB2B4145SoH0qtTGwbWNo40gZ",
	"tm2f55trjO/0j59T1q7jTLIxlcEByvgHhw1x2Lflnc9iD0d1MIX5XUiMyq00LodqI6E0C2WSwXXzTEse",
	"gMGs/5ep11ijUuLQStXIM/nz5YklxZqaEVPXU/XRaokVNNWx/K/Ljpw6rO0nOFyDI1WLdv03NsPZvdZt",
	"Eyna1u0mr/mN5ivmD/7Ix1Hu4226n6yu2NgAmnwwFmN2lea/eVQEGYSpqcR+9xpeIksNAM1lgZndcq+p",
	"fM92YdAqhHUcfcGaXJw+qJTuVUGGfPIF6Hb8NrNp64M7s7QYakfgee4I2MP8PpAH+oRi4thWcZV062b2",
	"8tefXl5d3oioJWmDIH3zaadH6v3BVQLDwa/3FcEuHPKZLWM3MXlj7KapAh1uPckqUDjwwRGW8TAcV+xN",
	"4EO4nFn03kShRfcvCZ0Dtcu7PUlmdoERDJueqCbvyRkUZ3Ugntv7mESmWg7OymYaZ7Zn6hzKWqPVDBL9",
	"o9jxxDwQkK9QsfzXcqA897HG4mNNbksjmWcGU2JsxYoSQGliq5vmaZojYSCRuztr3ZxQzJHa6RKkSysL",
	"ci5iGX38nCQooX+KQALgNBemma1YVMCKbUAHxoq7Yti0tdMdF+66vfJ/Y2lJL25mtjNqunwAW7WaZVdi",
	"EfeaAm8jJk4GOtaeWSmAm6FBuphDLhmiIAdb6Oxu47Q9a0dL40NMZGgdB96aIHW1de0i2VIsiPI0ZfQl",
	"zgSV1qcDle+slGfpYoUnh804DzUewsvY+G4zzT5nzKxgAbSYiaPH99WP0l4Jz6SmKFBkIWN9cLVK2Yaj",
	"aOJlk2e0LjaFyadPEsvkSAH9LBpO4gP6vANUGz/SIHOBv28MIJhx1BzbUN72ihSZNaXt/jOx2372ttO8",
	"2MC3dT2YO7kkAT+2oGjBG3OlImklRsWZjSmCwNXT++Z6Qnv3KuWfCktjV5wSeFG73W5mW3/KZX3odBaI",
	"Otc1L9/5luZ2L1SFv47Pxy9G8S9fj/96Ojk9x4uzF3QeB1Qajye4WODZRGmFxws8HSvU53R+jiM6PVss",
	"To/P9EjRBY1HF/pirh+bNu7SbdYv7nfHod88uujz5Hag3Qk+6fD/7e7mZWM9zf0bSPk2xWwIJF6IizEn",
	"ESw29+D6h5COrSMiTCbuRvBzY9H1hqz9q1VfG2KM9lV5GRMSATW56QbX7xFWKNHHC3V0HBKZOpeAn+7x",
	"lDMbTMWtDtGSkZCQkwmAYtdth0CSqzzk2WQ02Repsa7lNbddpwGeIbswBRnXstnMNoPB5i5ONKhybNu9",
	"/vCoYgOyL7T5fA+J39W3ajIg6BYExXWhY1t5Tg0unqtLugFdU1fkXUSVQ16wUBDCe7QCbk0QpDb6/9j7",
	"u2k9I5YWrKmh/g7QcmOVC4nRELCcxxiX0pfE4DO721GNnbGUxeZQsRMnspIygULPkZr7Yct74XZY1DZy",
	"vgNNFZuUgnRrLliiuZNGQuNkXxyzCydLE4fWG5/Z4bLH8vXtdQevl7x5K9QrmUsb52pXZNPsSDo8/z0A",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
