// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: consumer.sql

package dbgen

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const attachAttemptReferences = `-- name: AttachAttemptReferences :execrows
UPDATE payment_attempts
SET provider_session_id = coalesce(provider_session_id, $1),
    provider_payment_intent_id = coalesce(provider_payment_intent_id,
                                          $2),
    updated_at = now()
WHERE id = $3
  AND (provider_session_id IS NULL OR provider_session_id = $1)
`

type AttachAttemptReferencesParams struct {
	SessionID       sql.NullString
	PaymentIntentID sql.NullString
	ID              string
}

// Records the provider references on the attempt once an event confirms them.
//
// The session id is written only when the attempt does not have one yet. An
// attempt whose session id already differs is a correlation error the caller
// detects before reaching here; this clause makes the write itself incapable
// of overwriting a different session.
func (q *Queries) AttachAttemptReferences(ctx context.Context, arg AttachAttemptReferencesParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, attachAttemptReferences, arg.SessionID, arg.PaymentIntentID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const lockPaymentAggregate = `-- name: LockPaymentAggregate :one
SELECT o.id AS order_id, o.status AS order_status,
       p.id AS payment_id, p.status AS payment_status, p.provider AS provider,
       p.amount AS amount, p.currency AS currency,
       a.id AS attempt_id, a.status AS attempt_status,
       a.provider_session_id AS session_id
FROM payment_attempts a
JOIN payments p ON p.id = a.payment_id AND p.provider = a.provider
JOIN orders o ON o.id = p.order_id
WHERE a.id = $1
  AND p.id = $2
  AND o.id = $3
ORDER BY a.id, p.id, o.id
FOR UPDATE OF a, p, o
`

type LockPaymentAggregateParams struct {
	AttemptID string
	PaymentID string
	OrderID   string
}

type LockPaymentAggregateRow struct {
	OrderID       string
	OrderStatus   string
	PaymentID     string
	PaymentStatus string
	Provider      string
	Amount        int64
	Currency      string
	AttemptID     string
	AttemptStatus string
	SessionID     sql.NullString
}

// Locks the payment aggregate an event acts upon, in one statement.
//
// Locking only the inbox row is not enough: two *different* events of the same
// payment can be processed at once, read the same initial state and apply
// incompatible transitions. The join takes the attempt, its payment and the
// payment's order together, so events of one payment are serialized against
// each other.
//
// The rows are locked in a fixed order — attempt, payment, order — because two
// transactions taking the same locks in different orders would deadlock. The
// ORDER BY is what pins that order for the row-level locks PostgreSQL acquires
// while executing the join.
//
// The join itself is the correlation check: a row comes back only when the
// attempt really belongs to that payment and the payment to that order. A
// mismatch returns nothing, which the caller reports as an inconsistent
// reference rather than a missing row.
func (q *Queries) LockPaymentAggregate(ctx context.Context, arg LockPaymentAggregateParams) (LockPaymentAggregateRow, error) {
	row := q.db.QueryRowContext(ctx, lockPaymentAggregate, arg.AttemptID, arg.PaymentID, arg.OrderID)
	var i LockPaymentAggregateRow
	err := row.Scan(
		&i.OrderID,
		&i.OrderStatus,
		&i.PaymentID,
		&i.PaymentStatus,
		&i.Provider,
		&i.Amount,
		&i.Currency,
		&i.AttemptID,
		&i.AttemptStatus,
		&i.SessionID,
	)
	return i, err
}

const lockWebhookEvent = `-- name: LockWebhookEvent :one
SELECT id, provider, provider_event_id, event_type, raw_payload, payload,
       status, attempts, received_at
FROM webhook_events
WHERE id = $1
FOR UPDATE
`

type LockWebhookEventRow struct {
	ID              string
	Provider        string
	ProviderEventID string
	EventType       string
	RawPayload      []byte
	Payload         json.RawMessage
	Status          string
	Attempts        int32
	ReceivedAt      time.Time
}

// Locks the inbox entry the message refers to.
//
// This is the first lock of the transaction and the one that serializes two
// deliveries of the same event: a redelivery, or the relay republishing after
// a lease was lost. The second arrival blocks here until the first commits and
// then reads status = 'processed', which is what turns it into a no-op.
//
// The lock is blocking, not SKIP LOCKED. Skipping would mean acknowledging a
// message whose effect nobody applied, and if the transaction holding the row
// then rolled back the effect would be lost entirely.
func (q *Queries) LockWebhookEvent(ctx context.Context, id string) (LockWebhookEventRow, error) {
	row := q.db.QueryRowContext(ctx, lockWebhookEvent, id)
	var i LockWebhookEventRow
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.ProviderEventID,
		&i.EventType,
		&i.RawPayload,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.ReceivedAt,
	)
	return i, err
}

const markOrderPaid = `-- name: MarkOrderPaid :execrows
UPDATE orders
SET status = 'paid', updated_at = now()
WHERE id = $1
  AND status = 'pending'
`

// Marks an order paid. Only a pending order moves, so a late event can never
// revive one that was cancelled or expired.
func (q *Queries) MarkOrderPaid(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, markOrderPaid, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markWebhookEventProcessed = `-- name: MarkWebhookEventProcessed :execrows
UPDATE webhook_events
SET status = 'processed', processed_at = now(), attempts = attempts + 1,
    last_error = $1, updated_at = now()
WHERE id = $2
  AND status <> 'processed'
`

type MarkWebhookEventProcessedParams struct {
	Note sql.NullString
	ID   string
}

// Closes an inbox entry that produced its effect, or that was deliberately a
// no-op. Both are processed: the event has been dealt with and must never be
// applied again.
func (q *Queries) MarkWebhookEventProcessed(ctx context.Context, arg MarkWebhookEventProcessedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markWebhookEventProcessed, arg.Note, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const recordWebhookEventFailure = `-- name: RecordWebhookEventFailure :one
UPDATE webhook_events
SET attempts = attempts + 1,
    status = CASE
        WHEN $1::boolean
          OR attempts + 1 >= $2::integer
        THEN 'failed'
        ELSE status
    END,
    last_error = $3, updated_at = now()
WHERE id = $4
RETURNING attempts, status = 'failed' AS failed
`

type RecordWebhookEventFailureParams struct {
	Terminal    bool
	MaxAttempts int32
	LastError   sql.NullString
	ID          string
}

type RecordWebhookEventFailureRow struct {
	Attempts int32
	Failed   bool
}

// Records a failed attempt and atomically decides whether the inbox entry stays
// pending or is closed. The same statement that increments attempts compares
// the resulting value with the budget; doing that later in the service could
// publish the message to the DLQ while leaving this row pending.
func (q *Queries) RecordWebhookEventFailure(ctx context.Context, arg RecordWebhookEventFailureParams) (RecordWebhookEventFailureRow, error) {
	row := q.db.QueryRowContext(ctx, recordWebhookEventFailure,
		arg.Terminal,
		arg.MaxAttempts,
		arg.LastError,
		arg.ID,
	)
	var i RecordWebhookEventFailureRow
	err := row.Scan(&i.Attempts, &i.Failed)
	return i, err
}

const transitionPayment = `-- name: TransitionPayment :execrows
UPDATE payments
SET status = $1, updated_at = now()
WHERE id = $2
  AND status NOT IN (
      'succeeded', 'failed', 'cancelled', 'partially_refunded', 'refunded'
  )
`

type TransitionPaymentParams struct {
	Status string
	ID     string
}

// Moves a payment, refusing to leave a terminal financial state.
func (q *Queries) TransitionPayment(ctx context.Context, arg TransitionPaymentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, transitionPayment, arg.Status, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const transitionPaymentAttempt = `-- name: TransitionPaymentAttempt :execrows
UPDATE payment_attempts
SET status = $1, updated_at = now()
WHERE id = $2
  AND status NOT IN ('succeeded', 'failed', 'expired', 'cancelled')
`

type TransitionPaymentAttemptParams struct {
	Status string
	ID     string
}

// Moves an attempt, refusing to leave a settled state.
//
// The WHERE clause is the second line of defence. The transition matrix has
// already approved this write against state read under the lock, so this can
// only fail if the matrix and the schema disagree — and the caller treats zero
// rows during an approved transition as a violated invariant, not a no-op.
func (q *Queries) TransitionPaymentAttempt(ctx context.Context, arg TransitionPaymentAttemptParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, transitionPaymentAttempt, arg.Status, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const webhookInboxBacklog = `-- name: WebhookInboxBacklog :one
SELECT
    count(*) FILTER (WHERE status IN ('pending', 'processing')) AS pending,
    count(*) FILTER (WHERE status = 'failed') AS failed,
    coalesce(extract(epoch FROM now() - min(received_at) FILTER (
        WHERE status IN ('pending', 'processing'))), 0)::float8 AS oldest_age_seconds
FROM webhook_events
`

type WebhookInboxBacklogRow struct {
	Pending          int64
	Failed           int64
	OldestAgeSeconds float64
}

// Operational visibility: how many events are waiting or stuck.
func (q *Queries) WebhookInboxBacklog(ctx context.Context) (WebhookInboxBacklogRow, error) {
	row := q.db.QueryRowContext(ctx, webhookInboxBacklog)
	var i WebhookInboxBacklogRow
	err := row.Scan(&i.Pending, &i.Failed, &i.OldestAgeSeconds)
	return i, err
}
