// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: operations.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"
)

const getWebhookEvent = `-- name: GetWebhookEvent :one
SELECT e.id, e.provider, e.provider_event_id, e.event_type, e.status,
       e.attempts, e.received_at, e.processed_at, e.last_error, e.updated_at,
       e.replay_count, e.last_replayed_at,
       o.id AS outbox_id, o.status AS outbox_status,
       o.attempts AS outbox_attempts, o.published_at AS outbox_published_at,
       o.last_error AS outbox_last_error, o.next_attempt_at AS outbox_next_attempt_at
FROM webhook_events e
LEFT JOIN outbox_events o ON o.webhook_event_id = e.id
WHERE e.id = $1
`

type GetWebhookEventRow struct {
	ID                  string
	Provider            string
	ProviderEventID     string
	EventType           string
	Status              string
	Attempts            int32
	ReceivedAt          time.Time
	ProcessedAt         sql.NullTime
	LastError           sql.NullString
	UpdatedAt           time.Time
	ReplayCount         int32
	LastReplayedAt      sql.NullTime
	OutboxID            sql.NullString
	OutboxStatus        sql.NullString
	OutboxAttempts      sql.NullInt32
	OutboxPublishedAt   sql.NullTime
	OutboxLastError     sql.NullString
	OutboxNextAttemptAt sql.NullTime
}

func (q *Queries) GetWebhookEvent(ctx context.Context, id string) (GetWebhookEventRow, error) {
	row := q.db.QueryRowContext(ctx, getWebhookEvent, id)
	var i GetWebhookEventRow
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.ProviderEventID,
		&i.EventType,
		&i.Status,
		&i.Attempts,
		&i.ReceivedAt,
		&i.ProcessedAt,
		&i.LastError,
		&i.UpdatedAt,
		&i.ReplayCount,
		&i.LastReplayedAt,
		&i.OutboxID,
		&i.OutboxStatus,
		&i.OutboxAttempts,
		&i.OutboxPublishedAt,
		&i.OutboxLastError,
		&i.OutboxNextAttemptAt,
	)
	return i, err
}

const listWebhookEvents = `-- name: ListWebhookEvents :many
SELECT e.id, e.provider, e.provider_event_id, e.event_type, e.status,
       e.attempts, e.received_at, e.processed_at, e.last_error, e.updated_at,
       e.replay_count, e.last_replayed_at,
       o.id AS outbox_id, o.status AS outbox_status,
       o.attempts AS outbox_attempts, o.published_at AS outbox_published_at,
       o.last_error AS outbox_last_error, o.next_attempt_at AS outbox_next_attempt_at
FROM webhook_events e
LEFT JOIN outbox_events o ON o.webhook_event_id = e.id
WHERE $1::text = '' OR e.status = $1::text
ORDER BY e.received_at DESC, e.id DESC
LIMIT $2
`

type ListWebhookEventsParams struct {
	Status      string
	ResultLimit int32
}

type ListWebhookEventsRow struct {
	ID                  string
	Provider            string
	ProviderEventID     string
	EventType           string
	Status              string
	Attempts            int32
	ReceivedAt          time.Time
	ProcessedAt         sql.NullTime
	LastError           sql.NullString
	UpdatedAt           time.Time
	ReplayCount         int32
	LastReplayedAt      sql.NullTime
	OutboxID            sql.NullString
	OutboxStatus        sql.NullString
	OutboxAttempts      sql.NullInt32
	OutboxPublishedAt   sql.NullTime
	OutboxLastError     sql.NullString
	OutboxNextAttemptAt sql.NullTime
}

// Lists inbox entries without returning either stored payload. Provider
// payloads may contain customer data; the operational API exposes only the
// metadata needed to diagnose delivery and processing.
func (q *Queries) ListWebhookEvents(ctx context.Context, arg ListWebhookEventsParams) ([]ListWebhookEventsRow, error) {
	rows, err := q.db.QueryContext(ctx, listWebhookEvents, arg.Status, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWebhookEventsRow{}
	for rows.Next() {
		var i ListWebhookEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.ProviderEventID,
			&i.EventType,
			&i.Status,
			&i.Attempts,
			&i.ReceivedAt,
			&i.ProcessedAt,
			&i.LastError,
			&i.UpdatedAt,
			&i.ReplayCount,
			&i.LastReplayedAt,
			&i.OutboxID,
			&i.OutboxStatus,
			&i.OutboxAttempts,
			&i.OutboxPublishedAt,
			&i.OutboxLastError,
			&i.OutboxNextAttemptAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockWebhookEventForReplay = `-- name: LockWebhookEventForReplay :one
SELECT e.status AS event_status, o.status AS outbox_status
FROM webhook_events e
JOIN outbox_events o ON o.webhook_event_id = e.id
WHERE e.id = $1
FOR UPDATE OF e, o
`

type LockWebhookEventForReplayRow struct {
	EventStatus  string
	OutboxStatus string
}

// Both rows are locked before replay eligibility is checked. Concurrent
// requests therefore cannot count or enqueue the same replay twice.
func (q *Queries) LockWebhookEventForReplay(ctx context.Context, id string) (LockWebhookEventForReplayRow, error) {
	row := q.db.QueryRowContext(ctx, lockWebhookEventForReplay, id)
	var i LockWebhookEventForReplayRow
	err := row.Scan(&i.EventStatus, &i.OutboxStatus)
	return i, err
}

const resetOutboxForReplay = `-- name: ResetOutboxForReplay :execrows
UPDATE outbox_events
SET status = 'pending', attempts = 0, published_at = NULL, last_error = NULL,
    locked_until = NULL, locked_by = NULL, next_attempt_at = now(), updated_at = now()
WHERE webhook_event_id = $1
  AND status IN ('published', 'failed')
`

// Reuse the original outbox message instead of creating a second row. The
// inbox makes a repeated broker delivery harmless, while keeping one message
// id per provider event makes replay auditable and deterministic.
func (q *Queries) ResetOutboxForReplay(ctx context.Context, webhookEventID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, resetOutboxForReplay, webhookEventID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const resetWebhookEventForReplay = `-- name: ResetWebhookEventForReplay :execrows
UPDATE webhook_events
SET status = CASE WHEN status = 'failed' THEN 'pending' ELSE status END,
    attempts = CASE WHEN status = 'failed' THEN 0 ELSE attempts END,
    processed_at = CASE WHEN status = 'failed' THEN NULL ELSE processed_at END,
    last_error = CASE WHEN status = 'failed' THEN NULL ELSE last_error END,
    replay_count = replay_count + 1,
    last_replayed_at = now(),
    updated_at = now()
WHERE id = $1
  AND status IN ('pending', 'failed')
`

func (q *Queries) ResetWebhookEventForReplay(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, resetWebhookEventForReplay, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
