// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outbox.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"
)

const leaseOutboxBatch = `-- name: LeaseOutboxBatch :many
UPDATE outbox_events
SET status = 'publishing',
    locked_until = now() + make_interval(secs => $1::float8),
    locked_by = $2,
    updated_at = now()
WHERE id IN (
    SELECT o.id
    FROM outbox_events o
    WHERE o.next_attempt_at <= now()
      AND (o.status = 'pending'
           OR (o.status = 'publishing' AND o.locked_until <= now()))
    ORDER BY o.next_attempt_at
    LIMIT $3
    FOR UPDATE SKIP LOCKED
)
RETURNING id, webhook_event_id, event_type, schema_version, routing_key,
          correlation_id, occurred_at, attempts, locked_until
`

type LeaseOutboxBatchParams struct {
	LeaseSeconds float64
	Owner        sql.NullString
	BatchSize    int32
}

type LeaseOutboxBatchRow struct {
	ID             string
	WebhookEventID string
	EventType      string
	SchemaVersion  int32
	RoutingKey     string
	CorrelationID  string
	OccurredAt     time.Time
	Attempts       int32
	LockedUntil    sql.NullTime
}

// Leases a batch of due messages to one relay instance.
//
// The transaction around this is short and closes before any network I/O: the
// lease, not a held row lock, is what keeps two relays off the same message.
// FOR UPDATE SKIP LOCKED still matters, but only to keep two relays from
// racing on the claim itself, which takes microseconds.
//
// A row is due when it is pending past its backoff, or when it was leased and
// the holder never settled it before the deadline, which is how a relay that
// died releases its work.
//
// Every instant here comes from now(), never from the caller. PostgreSQL is the
// single clock: if instances computed deadlines against their own clocks, a
// machine running a few seconds fast would declare another instance's lease
// expired while it is still publishing.
func (q *Queries) LeaseOutboxBatch(ctx context.Context, arg LeaseOutboxBatchParams) ([]LeaseOutboxBatchRow, error) {
	rows, err := q.db.QueryContext(ctx, leaseOutboxBatch, arg.LeaseSeconds, arg.Owner, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LeaseOutboxBatchRow{}
	for rows.Next() {
		var i LeaseOutboxBatchRow
		if err := rows.Scan(
			&i.ID,
			&i.WebhookEventID,
			&i.EventType,
			&i.SchemaVersion,
			&i.RoutingKey,
			&i.CorrelationID,
			&i.OccurredAt,
			&i.Attempts,
			&i.LockedUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutboxFailed = `-- name: MarkOutboxFailed :execrows
UPDATE outbox_events
SET status = 'failed', attempts = attempts + 1, last_error = $1,
    locked_until = NULL, locked_by = NULL, updated_at = now()
WHERE id = $2
  AND locked_by = $3
  AND locked_until > now()
`

type MarkOutboxFailedParams struct {
	LastError sql.NullString
	ID        string
	Owner     sql.NullString
}

// Stops retrying a message the relay can never publish, such as one whose
// payload cannot be encoded. Reserved for errors classified as permanent;
// broker unavailability must never land here.
func (q *Queries) MarkOutboxFailed(ctx context.Context, arg MarkOutboxFailedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markOutboxFailed, arg.LastError, arg.ID, arg.Owner)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markOutboxPublished = `-- name: MarkOutboxPublished :execrows
UPDATE outbox_events
SET status = 'published', published_at = now(), attempts = attempts + 1,
    last_error = NULL, locked_until = NULL, locked_by = NULL, updated_at = now()
WHERE id = $1
  AND locked_by = $2
  AND locked_until > now()
`

type MarkOutboxPublishedParams struct {
	ID    string
	Owner sql.NullString
}

// Only ever called after the broker confirmed the publication.
//
// The lease must still be ours: locked_by identifies this exact process, and
// locked_until must not have passed, or another relay may already have taken
// the message over. Returning the row count is what lets the caller notice a
// lost lease instead of reporting a publication that was never recorded.
func (q *Queries) MarkOutboxPublished(ctx context.Context, arg MarkOutboxPublishedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markOutboxPublished, arg.ID, arg.Owner)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markOutboxRetryable = `-- name: MarkOutboxRetryable :execrows
UPDATE outbox_events
SET status = 'pending', attempts = attempts + 1, last_error = $1,
    next_attempt_at = now() + make_interval(secs => $2::float8),
    locked_until = NULL, locked_by = NULL, updated_at = now()
WHERE id = $3
  AND locked_by = $4
  AND locked_until > now()
`

type MarkOutboxRetryableParams struct {
	LastError      sql.NullString
	BackoffSeconds float64
	ID             string
	Owner          sql.NullString
}

// Returns the message to the pool with a backoff deadline. Transient failures
// never exhaust a budget; they simply wait longer before the next attempt.
func (q *Queries) MarkOutboxRetryable(ctx context.Context, arg MarkOutboxRetryableParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markOutboxRetryable,
		arg.LastError,
		arg.BackoffSeconds,
		arg.ID,
		arg.Owner,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const outboxBacklog = `-- name: OutboxBacklog :one
SELECT count(*) AS pending,
       coalesce(extract(epoch FROM now() - min(created_at)), 0)::float8 AS oldest_age_seconds
FROM outbox_events
WHERE status IN ('pending', 'publishing')
`

type OutboxBacklogRow struct {
	Pending          int64
	OldestAgeSeconds float64
}

// Operational visibility: how much work is waiting and how old it is.
func (q *Queries) OutboxBacklog(ctx context.Context) (OutboxBacklogRow, error) {
	row := q.db.QueryRowContext(ctx, outboxBacklog)
	var i OutboxBacklogRow
	err := row.Scan(&i.Pending, &i.OldestAgeSeconds)
	return i, err
}
