// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webhooks.sql

package dbgen

import (
	"context"
	"encoding/json"
	"time"
)

const insertOutboxEvent = `-- name: InsertOutboxEvent :exec
INSERT INTO outbox_events (
    id, webhook_event_id, event_type, schema_version, routing_key,
    correlation_id, occurred_at, status, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $9
)
`

type InsertOutboxEventParams struct {
	ID             string
	WebhookEventID string
	EventType      string
	SchemaVersion  int32
	RoutingKey     string
	CorrelationID  string
	OccurredAt     time.Time
	Status         string
	CreatedAt      time.Time
}

// Written in the same transaction as the event above.
func (q *Queries) InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) error {
	_, err := q.db.ExecContext(ctx, insertOutboxEvent,
		arg.ID,
		arg.WebhookEventID,
		arg.EventType,
		arg.SchemaVersion,
		arg.RoutingKey,
		arg.CorrelationID,
		arg.OccurredAt,
		arg.Status,
		arg.CreatedAt,
	)
	return err
}

const insertWebhookEvent = `-- name: InsertWebhookEvent :one
INSERT INTO webhook_events (
    id, provider, provider_event_id, event_type, raw_payload, payload, status, received_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $8
)
ON CONFLICT (provider, provider_event_id) DO NOTHING
RETURNING id
`

type InsertWebhookEventParams struct {
	ID              string
	Provider        string
	ProviderEventID string
	EventType       string
	RawPayload      []byte
	Payload         json.RawMessage
	Status          string
	ReceivedAt      time.Time
}

// Inserting the event is what deduplicates a redelivery: the unique index on
// (provider, provider_event_id) turns the second arrival into zero rows, and
// the caller learns it must not produce an outbox message.
func (q *Queries) InsertWebhookEvent(ctx context.Context, arg InsertWebhookEventParams) (string, error) {
	row := q.db.QueryRowContext(ctx, insertWebhookEvent,
		arg.ID,
		arg.Provider,
		arg.ProviderEventID,
		arg.EventType,
		arg.RawPayload,
		arg.Payload,
		arg.Status,
		arg.ReceivedAt,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}
