package orders

import (
	"crypto/rand"
	"encoding/hex"
	"errors"
	"fmt"
	"strings"
)

// IDPrefix marks public order identifiers.
const IDPrefix = "ord_"

// ErrInvalidID is returned when an order identifier has an invalid shape.
var ErrInvalidID = errors.New("invalid order id")

// NewID returns an opaque, non-sequential public identifier. It carries no
// timestamp or counter, so it leaks neither volume nor ordering.
func NewID() (string, error) {
	value := make([]byte, 16)
	if _, err := rand.Read(value); err != nil {
		return "", fmt.Errorf("generate order id: %w", err)
	}
	return IDPrefix + hex.EncodeToString(value), nil
}

// ValidateID rejects values that cannot be identifiers generated by NewID.
func ValidateID(id string) error {
	if len(id) != len(IDPrefix)+32 || !strings.HasPrefix(id, IDPrefix) {
		return ErrInvalidID
	}
	if _, err := hex.DecodeString(id[len(IDPrefix):]); err != nil {
		return ErrInvalidID
	}
	return nil
}
